// Automatically generated by odin 1.5.11 - do not edit
#include <float.h>
#include <R.h>
#include <Rmath.h>
#include <Rinternals.h>
#include <stdbool.h>
#include <R_ext/Rdynload.h>
#ifndef CINTERPOLTE_CINTERPOLATE_H_
#define CINTERPOLTE_CINTERPOLATE_H_

// Allow use from C++
#ifdef __cplusplus
extern "C" {
#endif

// There are only three functions in the interface; allocation,
// evaluation and freeing.

// Allocate an interpolation object.
//
//   type: The mode of interpolation. Must be one of "constant",
//       "linear" or "spline" (an R error is thrown if a different
//       value is given).
//
//   n: The number of `x` points to interpolate over
//
//   ny: the number of `y` points per `x` point.  This is 1 in the
//       case of zimple interpolation as used by Rs `interpolate()`
//
//   x: an array of `x` values of length `n`
//
//   y: an array of `ny` sets of `y` values.  This is in R's matrix
//       order (i.e., the first `n` values are the first series to
//       interpolate over).
//
//   fail_on_extrapolate: if true, when an extrapolation occurs throw
//       an error; if false return NA_REAL
//
//   auto_free: automatically clean up the interpolation object on
//       return to R. This uses `R_alloc` for allocations rather than
//       `Calloc` so freeing will always happen (even on error
//       elsewhere in the code). However, this prevents returning back
//       a pointer to R that will last longer than the call into C
//       code.
//
// The return value is an opaque pointer that can be passed through to
// `cinterpolate_eval` and `cinterpolate_free`
void *cinterpolate_alloc(const char *type, size_t n, size_t ny,
                         double *x, double *y, bool fail_on_extrapolate,
                         bool auto_free);

// Evaluate the interpolated function at a new `x` point.
//
//   x: A new, single, `x` point to interpolate `y` values to
//
//   obj: The interpolation object, as returned by `cinterpolate_alloc`
//
//   y: An array of length `ny` to store the interpolated values
//
// The return value is 0 if the interpolation is successful (with x
// lying within the range of values that the interpolation function
// supports), -1 otherwise
int cinterpolate_eval(double x, void *obj, double *y);

// Clean up all allocated memory
//
//   obj: The interpolation object, as returned by `cinterpolate_alloc`
void cinterpolate_free(void *obj);

#ifdef __cplusplus
}
#endif

#endif
typedef struct ocaode_internal {
  double *agein;
  double *BB;
  double *birthrisk;
  double *bz;
  int dim_agein;
  int dim_agein_1;
  int dim_agein_12;
  int dim_agein_123;
  int dim_agein_1234;
  int dim_agein_12345;
  int dim_agein_123456;
  int dim_agein_2;
  int dim_agein_3;
  int dim_agein_4;
  int dim_agein_5;
  int dim_agein_6;
  int dim_agein_7;
  int dim_BB;
  int dim_BB_1;
  int dim_BB_2;
  int dim_birthrisk;
  int dim_bz;
  int dim_immigration;
  int dim_immigration_1;
  int dim_immigration_12;
  int dim_immigration_2;
  int dim_immigration_3;
  int dim_In;
  int dim_In_1;
  int dim_In_2;
  int dim_migr;
  int dim_migr_1;
  int dim_migr_12;
  int dim_migr_123;
  int dim_migr_1234;
  int dim_migr_12345;
  int dim_migr_123456;
  int dim_migr_2;
  int dim_migr_3;
  int dim_migr_4;
  int dim_migr_5;
  int dim_migr_6;
  int dim_migr_7;
  int dim_migrage;
  int dim_migragein;
  int dim_migragein_1;
  int dim_migragein_12;
  int dim_migragein_123;
  int dim_migragein_1234;
  int dim_migragein_12345;
  int dim_migragein_123456;
  int dim_migragein_2;
  int dim_migragein_3;
  int dim_migragein_4;
  int dim_migragein_5;
  int dim_migragein_6;
  int dim_migragein_7;
  int dim_migrageout;
  int dim_migrageout_1;
  int dim_migrageout_12;
  int dim_migrageout_123;
  int dim_migrageout_1234;
  int dim_migrageout_12345;
  int dim_migrageout_123456;
  int dim_migrageout_2;
  int dim_migrageout_3;
  int dim_migrageout_4;
  int dim_migrageout_5;
  int dim_migrageout_6;
  int dim_migrageout_7;
  int dim_N;
  int dim_N_1;
  int dim_N_12;
  int dim_N_123;
  int dim_N_1234;
  int dim_N_12345;
  int dim_N_123456;
  int dim_N_2;
  int dim_N_3;
  int dim_N_4;
  int dim_N_5;
  int dim_N_6;
  int dim_N_7;
  int dim_native;
  int dim_omega;
  int dim_omega_1;
  int dim_omega_2;
  int dim_Pmigr_nat;
  int dim_Pmigr_post;
  int dim_Pmigr_post_1;
  int dim_Pmigr_post_2;
  int dim_Pmigr_prot;
  int dim_Pmigr_prot_1;
  int dim_Pmigr_prot_2;
  int dim_Pmigr_risk;
  int dim_Pmigr_risk_1;
  int dim_Pmigr_risk_2;
  int dim_Pmigr_strain;
  int dim_Pmigr_strain_1;
  int dim_Pmigr_strain_2;
  int dim_popdat;
  int dim_popdat_1;
  int dim_popdat_12;
  int dim_popdat_2;
  int dim_popdat_3;
  int dim_popinit;
  int dim_popinit_1;
  int dim_popinit_12;
  int dim_popinit_123;
  int dim_popinit_1234;
  int dim_popinit_12345;
  int dim_popinit_123456;
  int dim_popinit_2;
  int dim_popinit_3;
  int dim_popinit_4;
  int dim_popinit_5;
  int dim_popinit_6;
  int dim_popinit_7;
  int dim_r;
  int dim_RiskChange;
  int dim_RiskChange_1;
  int dim_RiskChange_12;
  int dim_RiskChange_123;
  int dim_RiskChange_1234;
  int dim_RiskChange_12345;
  int dim_RiskChange_123456;
  int dim_RiskChange_2;
  int dim_RiskChange_3;
  int dim_RiskChange_4;
  int dim_RiskChange_5;
  int dim_RiskChange_6;
  int dim_RiskChange_7;
  int dim_RiskHazard;
  int dim_RiskHazard_1;
  int dim_RiskHazard_12;
  int dim_RiskHazard_2;
  int dim_RiskHazard_3;
  int dim_RiskHazardData;
  int dim_RiskHazardData_1;
  int dim_RiskHazardData_12;
  int dim_RiskHazardData_123;
  int dim_RiskHazardData_2;
  int dim_RiskHazardData_3;
  int dim_RiskHazardData_4;
  int dim_tbbottom;
  int dim_tbbottom_1;
  int dim_tbbottom_12;
  int dim_tbbottom_2;
  int dim_tbbottom_3;
  int dim_ttp;
  double *immigration;
  double *In;
  double *initial_N;
  void *interpolate_bz;
  void *interpolate_In;
  void *interpolate_omega;
  void *interpolate_RiskHazard;
  int lttp;
  double *migr;
  double *migrage;
  double *migragein;
  double *migrageout;
  int nage;
  double *native;
  int nnat;
  int npost;
  int nprot;
  int nrisk;
  int nstrain;
  double *omega;
  double *Pmigr_nat;
  double *Pmigr_post;
  double *Pmigr_prot;
  double *Pmigr_risk;
  double *Pmigr_strain;
  double *popdat;
  double *popinit;
  double *r;
  double *RiskChange;
  double *RiskHazard;
  double *RiskHazardData;
  double *tbbottom;
  double *ttp;
} ocaode_internal;
ocaode_internal* ocaode_get_internal(SEXP internal_p, int closed_error);
static void ocaode_finalise(SEXP internal_p);
SEXP ocaode_create(SEXP user);
void ocaode_initmod_desolve(void(* odeparms) (int *, double *));
SEXP ocaode_contents(SEXP internal_p);
SEXP ocaode_set_user(SEXP internal_p, SEXP user);
SEXP ocaode_set_initial(SEXP internal_p, SEXP t_ptr, SEXP state_ptr, SEXP ocaode_use_dde_ptr);
SEXP ocaode_metadata(SEXP internal_p);
SEXP ocaode_initial_conditions(SEXP internal_p, SEXP t_ptr);
void ocaode_rhs(ocaode_internal* internal, double t, double * state, double * dstatedt, double * output);
void ocaode_rhs_dde(size_t neq, double t, double * state, double * dstatedt, void * internal);
void ocaode_rhs_desolve(int * neq, double * t, double * state, double * dstatedt, double * output, int * np);
SEXP ocaode_rhs_r(SEXP internal_p, SEXP t, SEXP state);
double user_get_scalar_double(SEXP user, const char *name,
                              double default_value, double min, double max);
int user_get_scalar_int(SEXP user, const char *name,
                        int default_value, double min, double max);
void user_check_values_double(double * value, size_t len,
                                  double min, double max, const char *name);
void user_check_values_int(int * value, size_t len,
                               double min, double max, const char *name);
void user_check_values(SEXP value, double min, double max,
                           const char *name);
SEXP user_list_element(SEXP list, const char *name);
void odin_set_dim(SEXP target, int rank, ...);
void* user_get_array_dim(SEXP user, bool is_integer, void * previous,
                         const char *name, int rank,
                         double min, double max, int *dest_dim);
void* user_get_array(SEXP user, bool is_integer, void * previous,
                     const char *name, double min, double max,
                     int rank, ...);
SEXP user_get_array_check(SEXP el, bool is_integer, const char *name,
                          double min, double max);
SEXP user_get_array_check_rank(SEXP user, const char *name, int rank,
                               bool required);
void interpolate_check_y(size_t nx, size_t ny, size_t i, const char *name_arg, const char *name_target);
double scalar_real(SEXP x, const char * name);
ocaode_internal* ocaode_get_internal(SEXP internal_p, int closed_error) {
  ocaode_internal *internal = NULL;
  if (TYPEOF(internal_p) != EXTPTRSXP) {
    Rf_error("Expected an external pointer");
  }
  internal = (ocaode_internal*) R_ExternalPtrAddr(internal_p);
  if (!internal && closed_error) {
    Rf_error("Pointer has been invalidated");
  }
  return internal;
}
void ocaode_finalise(SEXP internal_p) {
  ocaode_internal *internal = ocaode_get_internal(internal_p, 0);
  if (internal_p) {
    cinterpolate_free(internal->interpolate_bz);
    cinterpolate_free(internal->interpolate_In);
    cinterpolate_free(internal->interpolate_omega);
    cinterpolate_free(internal->interpolate_RiskHazard);
    internal->interpolate_bz = NULL;
    internal->interpolate_In = NULL;
    internal->interpolate_omega = NULL;
    internal->interpolate_RiskHazard = NULL;
    R_Free(internal->agein);
    R_Free(internal->BB);
    R_Free(internal->birthrisk);
    R_Free(internal->bz);
    R_Free(internal->immigration);
    R_Free(internal->In);
    R_Free(internal->initial_N);
    R_Free(internal->migr);
    R_Free(internal->migrage);
    R_Free(internal->migragein);
    R_Free(internal->migrageout);
    R_Free(internal->native);
    R_Free(internal->omega);
    R_Free(internal->Pmigr_nat);
    R_Free(internal->Pmigr_post);
    R_Free(internal->Pmigr_prot);
    R_Free(internal->Pmigr_risk);
    R_Free(internal->Pmigr_strain);
    R_Free(internal->popdat);
    R_Free(internal->popinit);
    R_Free(internal->r);
    R_Free(internal->RiskChange);
    R_Free(internal->RiskHazard);
    R_Free(internal->RiskHazardData);
    R_Free(internal->tbbottom);
    R_Free(internal->ttp);
    R_Free(internal);
    R_ClearExternalPtr(internal_p);
  }
}
SEXP ocaode_create(SEXP user) {
  ocaode_internal *internal = (ocaode_internal*) R_Calloc(1, ocaode_internal);
  internal->agein = NULL;
  internal->BB = NULL;
  internal->birthrisk = NULL;
  internal->bz = NULL;
  internal->immigration = NULL;
  internal->In = NULL;
  internal->initial_N = NULL;
  internal->interpolate_bz = NULL;
  internal->interpolate_In = NULL;
  internal->interpolate_omega = NULL;
  internal->interpolate_RiskHazard = NULL;
  internal->migr = NULL;
  internal->migrage = NULL;
  internal->migragein = NULL;
  internal->migrageout = NULL;
  internal->native = NULL;
  internal->omega = NULL;
  internal->Pmigr_nat = NULL;
  internal->Pmigr_post = NULL;
  internal->Pmigr_prot = NULL;
  internal->Pmigr_risk = NULL;
  internal->Pmigr_strain = NULL;
  internal->popdat = NULL;
  internal->popinit = NULL;
  internal->r = NULL;
  internal->RiskChange = NULL;
  internal->RiskHazard = NULL;
  internal->RiskHazardData = NULL;
  internal->tbbottom = NULL;
  internal->ttp = NULL;
  internal->dim_bz = 2;
  R_Free(internal->bz);
  internal->bz = (double*) R_Calloc(internal->dim_bz, double);
  internal->BB = NULL;
  internal->birthrisk = NULL;
  internal->immigration = NULL;
  internal->migrage = NULL;
  internal->nage = NA_INTEGER;
  internal->nnat = NA_INTEGER;
  internal->npost = NA_INTEGER;
  internal->nprot = NA_INTEGER;
  internal->nrisk = NA_INTEGER;
  internal->nstrain = NA_INTEGER;
  internal->Pmigr_post = NULL;
  internal->Pmigr_prot = NULL;
  internal->Pmigr_risk = NULL;
  internal->Pmigr_strain = NULL;
  internal->popdat = NULL;
  internal->popinit = NULL;
  internal->r = NULL;
  internal->RiskHazardData = NULL;
  internal->ttp = NULL;
  SEXP ptr = PROTECT(R_MakeExternalPtr(internal, R_NilValue, R_NilValue));
  R_RegisterCFinalizer(ptr, ocaode_finalise);
  UNPROTECT(1);
  return ptr;
}
static ocaode_internal *ocaode_internal_ds;
void ocaode_initmod_desolve(void(* odeparms) (int *, double *)) {
  static DL_FUNC get_desolve_gparms = NULL;
  if (get_desolve_gparms == NULL) {
    get_desolve_gparms =
      R_GetCCallable("deSolve", "get_deSolve_gparms");
  }
  ocaode_internal_ds = ocaode_get_internal(get_desolve_gparms(), 1);
}
SEXP ocaode_contents(SEXP internal_p) {
  ocaode_internal *internal = ocaode_get_internal(internal_p, 1);
  SEXP contents = PROTECT(allocVector(VECSXP, 183));
  SEXP agein = PROTECT(allocVector(REALSXP, internal->dim_agein));
  memcpy(REAL(agein), internal->agein, internal->dim_agein * sizeof(double));
  odin_set_dim(agein, 7, internal->dim_agein_1, internal->dim_agein_2, internal->dim_agein_3, internal->dim_agein_4, internal->dim_agein_5, internal->dim_agein_6, internal->dim_agein_7);
  SET_VECTOR_ELT(contents, 0, agein);
  SEXP BB = PROTECT(allocVector(REALSXP, internal->dim_BB));
  memcpy(REAL(BB), internal->BB, internal->dim_BB * sizeof(double));
  odin_set_dim(BB, 2, internal->dim_BB_1, internal->dim_BB_2);
  SET_VECTOR_ELT(contents, 1, BB);
  SEXP birthrisk = PROTECT(allocVector(REALSXP, internal->dim_birthrisk));
  memcpy(REAL(birthrisk), internal->birthrisk, internal->dim_birthrisk * sizeof(double));
  SET_VECTOR_ELT(contents, 2, birthrisk);
  SEXP bz = PROTECT(allocVector(REALSXP, internal->dim_bz));
  memcpy(REAL(bz), internal->bz, internal->dim_bz * sizeof(double));
  SET_VECTOR_ELT(contents, 3, bz);
  SET_VECTOR_ELT(contents, 4, ScalarInteger(internal->dim_agein));
  SET_VECTOR_ELT(contents, 5, ScalarInteger(internal->dim_agein_1));
  SET_VECTOR_ELT(contents, 6, ScalarInteger(internal->dim_agein_12));
  SET_VECTOR_ELT(contents, 7, ScalarInteger(internal->dim_agein_123));
  SET_VECTOR_ELT(contents, 8, ScalarInteger(internal->dim_agein_1234));
  SET_VECTOR_ELT(contents, 9, ScalarInteger(internal->dim_agein_12345));
  SET_VECTOR_ELT(contents, 10, ScalarInteger(internal->dim_agein_123456));
  SET_VECTOR_ELT(contents, 11, ScalarInteger(internal->dim_agein_2));
  SET_VECTOR_ELT(contents, 12, ScalarInteger(internal->dim_agein_3));
  SET_VECTOR_ELT(contents, 13, ScalarInteger(internal->dim_agein_4));
  SET_VECTOR_ELT(contents, 14, ScalarInteger(internal->dim_agein_5));
  SET_VECTOR_ELT(contents, 15, ScalarInteger(internal->dim_agein_6));
  SET_VECTOR_ELT(contents, 16, ScalarInteger(internal->dim_agein_7));
  SET_VECTOR_ELT(contents, 17, ScalarInteger(internal->dim_BB));
  SET_VECTOR_ELT(contents, 18, ScalarInteger(internal->dim_BB_1));
  SET_VECTOR_ELT(contents, 19, ScalarInteger(internal->dim_BB_2));
  SET_VECTOR_ELT(contents, 20, ScalarInteger(internal->dim_birthrisk));
  SET_VECTOR_ELT(contents, 21, ScalarInteger(internal->dim_bz));
  SET_VECTOR_ELT(contents, 22, ScalarInteger(internal->dim_immigration));
  SET_VECTOR_ELT(contents, 23, ScalarInteger(internal->dim_immigration_1));
  SET_VECTOR_ELT(contents, 24, ScalarInteger(internal->dim_immigration_12));
  SET_VECTOR_ELT(contents, 25, ScalarInteger(internal->dim_immigration_2));
  SET_VECTOR_ELT(contents, 26, ScalarInteger(internal->dim_immigration_3));
  SET_VECTOR_ELT(contents, 27, ScalarInteger(internal->dim_In));
  SET_VECTOR_ELT(contents, 28, ScalarInteger(internal->dim_In_1));
  SET_VECTOR_ELT(contents, 29, ScalarInteger(internal->dim_In_2));
  SET_VECTOR_ELT(contents, 30, ScalarInteger(internal->dim_migr));
  SET_VECTOR_ELT(contents, 31, ScalarInteger(internal->dim_migr_1));
  SET_VECTOR_ELT(contents, 32, ScalarInteger(internal->dim_migr_12));
  SET_VECTOR_ELT(contents, 33, ScalarInteger(internal->dim_migr_123));
  SET_VECTOR_ELT(contents, 34, ScalarInteger(internal->dim_migr_1234));
  SET_VECTOR_ELT(contents, 35, ScalarInteger(internal->dim_migr_12345));
  SET_VECTOR_ELT(contents, 36, ScalarInteger(internal->dim_migr_123456));
  SET_VECTOR_ELT(contents, 37, ScalarInteger(internal->dim_migr_2));
  SET_VECTOR_ELT(contents, 38, ScalarInteger(internal->dim_migr_3));
  SET_VECTOR_ELT(contents, 39, ScalarInteger(internal->dim_migr_4));
  SET_VECTOR_ELT(contents, 40, ScalarInteger(internal->dim_migr_5));
  SET_VECTOR_ELT(contents, 41, ScalarInteger(internal->dim_migr_6));
  SET_VECTOR_ELT(contents, 42, ScalarInteger(internal->dim_migr_7));
  SET_VECTOR_ELT(contents, 43, ScalarInteger(internal->dim_migrage));
  SET_VECTOR_ELT(contents, 44, ScalarInteger(internal->dim_migragein));
  SET_VECTOR_ELT(contents, 45, ScalarInteger(internal->dim_migragein_1));
  SET_VECTOR_ELT(contents, 46, ScalarInteger(internal->dim_migragein_12));
  SET_VECTOR_ELT(contents, 47, ScalarInteger(internal->dim_migragein_123));
  SET_VECTOR_ELT(contents, 48, ScalarInteger(internal->dim_migragein_1234));
  SET_VECTOR_ELT(contents, 49, ScalarInteger(internal->dim_migragein_12345));
  SET_VECTOR_ELT(contents, 50, ScalarInteger(internal->dim_migragein_123456));
  SET_VECTOR_ELT(contents, 51, ScalarInteger(internal->dim_migragein_2));
  SET_VECTOR_ELT(contents, 52, ScalarInteger(internal->dim_migragein_3));
  SET_VECTOR_ELT(contents, 53, ScalarInteger(internal->dim_migragein_4));
  SET_VECTOR_ELT(contents, 54, ScalarInteger(internal->dim_migragein_5));
  SET_VECTOR_ELT(contents, 55, ScalarInteger(internal->dim_migragein_6));
  SET_VECTOR_ELT(contents, 56, ScalarInteger(internal->dim_migragein_7));
  SET_VECTOR_ELT(contents, 57, ScalarInteger(internal->dim_migrageout));
  SET_VECTOR_ELT(contents, 58, ScalarInteger(internal->dim_migrageout_1));
  SET_VECTOR_ELT(contents, 59, ScalarInteger(internal->dim_migrageout_12));
  SET_VECTOR_ELT(contents, 60, ScalarInteger(internal->dim_migrageout_123));
  SET_VECTOR_ELT(contents, 61, ScalarInteger(internal->dim_migrageout_1234));
  SET_VECTOR_ELT(contents, 62, ScalarInteger(internal->dim_migrageout_12345));
  SET_VECTOR_ELT(contents, 63, ScalarInteger(internal->dim_migrageout_123456));
  SET_VECTOR_ELT(contents, 64, ScalarInteger(internal->dim_migrageout_2));
  SET_VECTOR_ELT(contents, 65, ScalarInteger(internal->dim_migrageout_3));
  SET_VECTOR_ELT(contents, 66, ScalarInteger(internal->dim_migrageout_4));
  SET_VECTOR_ELT(contents, 67, ScalarInteger(internal->dim_migrageout_5));
  SET_VECTOR_ELT(contents, 68, ScalarInteger(internal->dim_migrageout_6));
  SET_VECTOR_ELT(contents, 69, ScalarInteger(internal->dim_migrageout_7));
  SET_VECTOR_ELT(contents, 70, ScalarInteger(internal->dim_N));
  SET_VECTOR_ELT(contents, 71, ScalarInteger(internal->dim_N_1));
  SET_VECTOR_ELT(contents, 72, ScalarInteger(internal->dim_N_12));
  SET_VECTOR_ELT(contents, 73, ScalarInteger(internal->dim_N_123));
  SET_VECTOR_ELT(contents, 74, ScalarInteger(internal->dim_N_1234));
  SET_VECTOR_ELT(contents, 75, ScalarInteger(internal->dim_N_12345));
  SET_VECTOR_ELT(contents, 76, ScalarInteger(internal->dim_N_123456));
  SET_VECTOR_ELT(contents, 77, ScalarInteger(internal->dim_N_2));
  SET_VECTOR_ELT(contents, 78, ScalarInteger(internal->dim_N_3));
  SET_VECTOR_ELT(contents, 79, ScalarInteger(internal->dim_N_4));
  SET_VECTOR_ELT(contents, 80, ScalarInteger(internal->dim_N_5));
  SET_VECTOR_ELT(contents, 81, ScalarInteger(internal->dim_N_6));
  SET_VECTOR_ELT(contents, 82, ScalarInteger(internal->dim_N_7));
  SET_VECTOR_ELT(contents, 83, ScalarInteger(internal->dim_native));
  SET_VECTOR_ELT(contents, 84, ScalarInteger(internal->dim_omega));
  SET_VECTOR_ELT(contents, 85, ScalarInteger(internal->dim_omega_1));
  SET_VECTOR_ELT(contents, 86, ScalarInteger(internal->dim_omega_2));
  SET_VECTOR_ELT(contents, 87, ScalarInteger(internal->dim_Pmigr_nat));
  SET_VECTOR_ELT(contents, 88, ScalarInteger(internal->dim_Pmigr_post));
  SET_VECTOR_ELT(contents, 89, ScalarInteger(internal->dim_Pmigr_post_1));
  SET_VECTOR_ELT(contents, 90, ScalarInteger(internal->dim_Pmigr_post_2));
  SET_VECTOR_ELT(contents, 91, ScalarInteger(internal->dim_Pmigr_prot));
  SET_VECTOR_ELT(contents, 92, ScalarInteger(internal->dim_Pmigr_prot_1));
  SET_VECTOR_ELT(contents, 93, ScalarInteger(internal->dim_Pmigr_prot_2));
  SET_VECTOR_ELT(contents, 94, ScalarInteger(internal->dim_Pmigr_risk));
  SET_VECTOR_ELT(contents, 95, ScalarInteger(internal->dim_Pmigr_risk_1));
  SET_VECTOR_ELT(contents, 96, ScalarInteger(internal->dim_Pmigr_risk_2));
  SET_VECTOR_ELT(contents, 97, ScalarInteger(internal->dim_Pmigr_strain));
  SET_VECTOR_ELT(contents, 98, ScalarInteger(internal->dim_Pmigr_strain_1));
  SET_VECTOR_ELT(contents, 99, ScalarInteger(internal->dim_Pmigr_strain_2));
  SET_VECTOR_ELT(contents, 100, ScalarInteger(internal->dim_popdat));
  SET_VECTOR_ELT(contents, 101, ScalarInteger(internal->dim_popdat_1));
  SET_VECTOR_ELT(contents, 102, ScalarInteger(internal->dim_popdat_12));
  SET_VECTOR_ELT(contents, 103, ScalarInteger(internal->dim_popdat_2));
  SET_VECTOR_ELT(contents, 104, ScalarInteger(internal->dim_popdat_3));
  SET_VECTOR_ELT(contents, 105, ScalarInteger(internal->dim_popinit));
  SET_VECTOR_ELT(contents, 106, ScalarInteger(internal->dim_popinit_1));
  SET_VECTOR_ELT(contents, 107, ScalarInteger(internal->dim_popinit_12));
  SET_VECTOR_ELT(contents, 108, ScalarInteger(internal->dim_popinit_123));
  SET_VECTOR_ELT(contents, 109, ScalarInteger(internal->dim_popinit_1234));
  SET_VECTOR_ELT(contents, 110, ScalarInteger(internal->dim_popinit_12345));
  SET_VECTOR_ELT(contents, 111, ScalarInteger(internal->dim_popinit_123456));
  SET_VECTOR_ELT(contents, 112, ScalarInteger(internal->dim_popinit_2));
  SET_VECTOR_ELT(contents, 113, ScalarInteger(internal->dim_popinit_3));
  SET_VECTOR_ELT(contents, 114, ScalarInteger(internal->dim_popinit_4));
  SET_VECTOR_ELT(contents, 115, ScalarInteger(internal->dim_popinit_5));
  SET_VECTOR_ELT(contents, 116, ScalarInteger(internal->dim_popinit_6));
  SET_VECTOR_ELT(contents, 117, ScalarInteger(internal->dim_popinit_7));
  SET_VECTOR_ELT(contents, 118, ScalarInteger(internal->dim_r));
  SET_VECTOR_ELT(contents, 119, ScalarInteger(internal->dim_RiskChange));
  SET_VECTOR_ELT(contents, 120, ScalarInteger(internal->dim_RiskChange_1));
  SET_VECTOR_ELT(contents, 121, ScalarInteger(internal->dim_RiskChange_12));
  SET_VECTOR_ELT(contents, 122, ScalarInteger(internal->dim_RiskChange_123));
  SET_VECTOR_ELT(contents, 123, ScalarInteger(internal->dim_RiskChange_1234));
  SET_VECTOR_ELT(contents, 124, ScalarInteger(internal->dim_RiskChange_12345));
  SET_VECTOR_ELT(contents, 125, ScalarInteger(internal->dim_RiskChange_123456));
  SET_VECTOR_ELT(contents, 126, ScalarInteger(internal->dim_RiskChange_2));
  SET_VECTOR_ELT(contents, 127, ScalarInteger(internal->dim_RiskChange_3));
  SET_VECTOR_ELT(contents, 128, ScalarInteger(internal->dim_RiskChange_4));
  SET_VECTOR_ELT(contents, 129, ScalarInteger(internal->dim_RiskChange_5));
  SET_VECTOR_ELT(contents, 130, ScalarInteger(internal->dim_RiskChange_6));
  SET_VECTOR_ELT(contents, 131, ScalarInteger(internal->dim_RiskChange_7));
  SET_VECTOR_ELT(contents, 132, ScalarInteger(internal->dim_RiskHazard));
  SET_VECTOR_ELT(contents, 133, ScalarInteger(internal->dim_RiskHazard_1));
  SET_VECTOR_ELT(contents, 134, ScalarInteger(internal->dim_RiskHazard_12));
  SET_VECTOR_ELT(contents, 135, ScalarInteger(internal->dim_RiskHazard_2));
  SET_VECTOR_ELT(contents, 136, ScalarInteger(internal->dim_RiskHazard_3));
  SET_VECTOR_ELT(contents, 137, ScalarInteger(internal->dim_RiskHazardData));
  SET_VECTOR_ELT(contents, 138, ScalarInteger(internal->dim_RiskHazardData_1));
  SET_VECTOR_ELT(contents, 139, ScalarInteger(internal->dim_RiskHazardData_12));
  SET_VECTOR_ELT(contents, 140, ScalarInteger(internal->dim_RiskHazardData_123));
  SET_VECTOR_ELT(contents, 141, ScalarInteger(internal->dim_RiskHazardData_2));
  SET_VECTOR_ELT(contents, 142, ScalarInteger(internal->dim_RiskHazardData_3));
  SET_VECTOR_ELT(contents, 143, ScalarInteger(internal->dim_RiskHazardData_4));
  SET_VECTOR_ELT(contents, 144, ScalarInteger(internal->dim_tbbottom));
  SET_VECTOR_ELT(contents, 145, ScalarInteger(internal->dim_tbbottom_1));
  SET_VECTOR_ELT(contents, 146, ScalarInteger(internal->dim_tbbottom_12));
  SET_VECTOR_ELT(contents, 147, ScalarInteger(internal->dim_tbbottom_2));
  SET_VECTOR_ELT(contents, 148, ScalarInteger(internal->dim_tbbottom_3));
  SET_VECTOR_ELT(contents, 149, ScalarInteger(internal->dim_ttp));
  SEXP immigration = PROTECT(allocVector(REALSXP, internal->dim_immigration));
  memcpy(REAL(immigration), internal->immigration, internal->dim_immigration * sizeof(double));
  odin_set_dim(immigration, 3, internal->dim_immigration_1, internal->dim_immigration_2, internal->dim_immigration_3);
  SET_VECTOR_ELT(contents, 150, immigration);
  SEXP In = PROTECT(allocVector(REALSXP, internal->dim_In));
  memcpy(REAL(In), internal->In, internal->dim_In * sizeof(double));
  odin_set_dim(In, 2, internal->dim_In_1, internal->dim_In_2);
  SET_VECTOR_ELT(contents, 151, In);
  SEXP initial_N = PROTECT(allocVector(REALSXP, internal->dim_N));
  memcpy(REAL(initial_N), internal->initial_N, internal->dim_N * sizeof(double));
  odin_set_dim(initial_N, 7, internal->dim_N_1, internal->dim_N_2, internal->dim_N_3, internal->dim_N_4, internal->dim_N_5, internal->dim_N_6, internal->dim_N_7);
  SET_VECTOR_ELT(contents, 152, initial_N);
  SET_VECTOR_ELT(contents, 157, ScalarInteger(internal->lttp));
  SEXP migr = PROTECT(allocVector(REALSXP, internal->dim_migr));
  memcpy(REAL(migr), internal->migr, internal->dim_migr * sizeof(double));
  odin_set_dim(migr, 7, internal->dim_migr_1, internal->dim_migr_2, internal->dim_migr_3, internal->dim_migr_4, internal->dim_migr_5, internal->dim_migr_6, internal->dim_migr_7);
  SET_VECTOR_ELT(contents, 158, migr);
  SEXP migrage = PROTECT(allocVector(REALSXP, internal->dim_migrage));
  memcpy(REAL(migrage), internal->migrage, internal->dim_migrage * sizeof(double));
  SET_VECTOR_ELT(contents, 159, migrage);
  SEXP migragein = PROTECT(allocVector(REALSXP, internal->dim_migragein));
  memcpy(REAL(migragein), internal->migragein, internal->dim_migragein * sizeof(double));
  odin_set_dim(migragein, 7, internal->dim_migragein_1, internal->dim_migragein_2, internal->dim_migragein_3, internal->dim_migragein_4, internal->dim_migragein_5, internal->dim_migragein_6, internal->dim_migragein_7);
  SET_VECTOR_ELT(contents, 160, migragein);
  SEXP migrageout = PROTECT(allocVector(REALSXP, internal->dim_migrageout));
  memcpy(REAL(migrageout), internal->migrageout, internal->dim_migrageout * sizeof(double));
  odin_set_dim(migrageout, 7, internal->dim_migrageout_1, internal->dim_migrageout_2, internal->dim_migrageout_3, internal->dim_migrageout_4, internal->dim_migrageout_5, internal->dim_migrageout_6, internal->dim_migrageout_7);
  SET_VECTOR_ELT(contents, 161, migrageout);
  SET_VECTOR_ELT(contents, 162, ScalarInteger(internal->nage));
  SEXP native = PROTECT(allocVector(REALSXP, internal->dim_native));
  memcpy(REAL(native), internal->native, internal->dim_native * sizeof(double));
  SET_VECTOR_ELT(contents, 163, native);
  SET_VECTOR_ELT(contents, 164, ScalarInteger(internal->nnat));
  SET_VECTOR_ELT(contents, 165, ScalarInteger(internal->npost));
  SET_VECTOR_ELT(contents, 166, ScalarInteger(internal->nprot));
  SET_VECTOR_ELT(contents, 167, ScalarInteger(internal->nrisk));
  SET_VECTOR_ELT(contents, 168, ScalarInteger(internal->nstrain));
  SEXP omega = PROTECT(allocVector(REALSXP, internal->dim_omega));
  memcpy(REAL(omega), internal->omega, internal->dim_omega * sizeof(double));
  odin_set_dim(omega, 2, internal->dim_omega_1, internal->dim_omega_2);
  SET_VECTOR_ELT(contents, 169, omega);
  SEXP Pmigr_nat = PROTECT(allocVector(REALSXP, internal->dim_Pmigr_nat));
  memcpy(REAL(Pmigr_nat), internal->Pmigr_nat, internal->dim_Pmigr_nat * sizeof(double));
  SET_VECTOR_ELT(contents, 170, Pmigr_nat);
  SEXP Pmigr_post = PROTECT(allocVector(REALSXP, internal->dim_Pmigr_post));
  memcpy(REAL(Pmigr_post), internal->Pmigr_post, internal->dim_Pmigr_post * sizeof(double));
  odin_set_dim(Pmigr_post, 2, internal->dim_Pmigr_post_1, internal->dim_Pmigr_post_2);
  SET_VECTOR_ELT(contents, 171, Pmigr_post);
  SEXP Pmigr_prot = PROTECT(allocVector(REALSXP, internal->dim_Pmigr_prot));
  memcpy(REAL(Pmigr_prot), internal->Pmigr_prot, internal->dim_Pmigr_prot * sizeof(double));
  odin_set_dim(Pmigr_prot, 2, internal->dim_Pmigr_prot_1, internal->dim_Pmigr_prot_2);
  SET_VECTOR_ELT(contents, 172, Pmigr_prot);
  SEXP Pmigr_risk = PROTECT(allocVector(REALSXP, internal->dim_Pmigr_risk));
  memcpy(REAL(Pmigr_risk), internal->Pmigr_risk, internal->dim_Pmigr_risk * sizeof(double));
  odin_set_dim(Pmigr_risk, 2, internal->dim_Pmigr_risk_1, internal->dim_Pmigr_risk_2);
  SET_VECTOR_ELT(contents, 173, Pmigr_risk);
  SEXP Pmigr_strain = PROTECT(allocVector(REALSXP, internal->dim_Pmigr_strain));
  memcpy(REAL(Pmigr_strain), internal->Pmigr_strain, internal->dim_Pmigr_strain * sizeof(double));
  odin_set_dim(Pmigr_strain, 2, internal->dim_Pmigr_strain_1, internal->dim_Pmigr_strain_2);
  SET_VECTOR_ELT(contents, 174, Pmigr_strain);
  SEXP popdat = PROTECT(allocVector(REALSXP, internal->dim_popdat));
  memcpy(REAL(popdat), internal->popdat, internal->dim_popdat * sizeof(double));
  odin_set_dim(popdat, 3, internal->dim_popdat_1, internal->dim_popdat_2, internal->dim_popdat_3);
  SET_VECTOR_ELT(contents, 175, popdat);
  SEXP popinit = PROTECT(allocVector(REALSXP, internal->dim_popinit));
  memcpy(REAL(popinit), internal->popinit, internal->dim_popinit * sizeof(double));
  odin_set_dim(popinit, 7, internal->dim_popinit_1, internal->dim_popinit_2, internal->dim_popinit_3, internal->dim_popinit_4, internal->dim_popinit_5, internal->dim_popinit_6, internal->dim_popinit_7);
  SET_VECTOR_ELT(contents, 176, popinit);
  SEXP r = PROTECT(allocVector(REALSXP, internal->dim_r));
  memcpy(REAL(r), internal->r, internal->dim_r * sizeof(double));
  SET_VECTOR_ELT(contents, 177, r);
  SEXP RiskChange = PROTECT(allocVector(REALSXP, internal->dim_RiskChange));
  memcpy(REAL(RiskChange), internal->RiskChange, internal->dim_RiskChange * sizeof(double));
  odin_set_dim(RiskChange, 7, internal->dim_RiskChange_1, internal->dim_RiskChange_2, internal->dim_RiskChange_3, internal->dim_RiskChange_4, internal->dim_RiskChange_5, internal->dim_RiskChange_6, internal->dim_RiskChange_7);
  SET_VECTOR_ELT(contents, 178, RiskChange);
  SEXP RiskHazard = PROTECT(allocVector(REALSXP, internal->dim_RiskHazard));
  memcpy(REAL(RiskHazard), internal->RiskHazard, internal->dim_RiskHazard * sizeof(double));
  odin_set_dim(RiskHazard, 3, internal->dim_RiskHazard_1, internal->dim_RiskHazard_2, internal->dim_RiskHazard_3);
  SET_VECTOR_ELT(contents, 179, RiskHazard);
  SEXP RiskHazardData = PROTECT(allocVector(REALSXP, internal->dim_RiskHazardData));
  memcpy(REAL(RiskHazardData), internal->RiskHazardData, internal->dim_RiskHazardData * sizeof(double));
  odin_set_dim(RiskHazardData, 4, internal->dim_RiskHazardData_1, internal->dim_RiskHazardData_2, internal->dim_RiskHazardData_3, internal->dim_RiskHazardData_4);
  SET_VECTOR_ELT(contents, 180, RiskHazardData);
  SEXP tbbottom = PROTECT(allocVector(REALSXP, internal->dim_tbbottom));
  memcpy(REAL(tbbottom), internal->tbbottom, internal->dim_tbbottom * sizeof(double));
  odin_set_dim(tbbottom, 3, internal->dim_tbbottom_1, internal->dim_tbbottom_2, internal->dim_tbbottom_3);
  SET_VECTOR_ELT(contents, 181, tbbottom);
  SEXP ttp = PROTECT(allocVector(REALSXP, internal->dim_ttp));
  memcpy(REAL(ttp), internal->ttp, internal->dim_ttp * sizeof(double));
  SET_VECTOR_ELT(contents, 182, ttp);
  SEXP nms = PROTECT(allocVector(STRSXP, 183));
  SET_STRING_ELT(nms, 0, mkChar("agein"));
  SET_STRING_ELT(nms, 1, mkChar("BB"));
  SET_STRING_ELT(nms, 2, mkChar("birthrisk"));
  SET_STRING_ELT(nms, 3, mkChar("bz"));
  SET_STRING_ELT(nms, 4, mkChar("dim_agein"));
  SET_STRING_ELT(nms, 5, mkChar("dim_agein_1"));
  SET_STRING_ELT(nms, 6, mkChar("dim_agein_12"));
  SET_STRING_ELT(nms, 7, mkChar("dim_agein_123"));
  SET_STRING_ELT(nms, 8, mkChar("dim_agein_1234"));
  SET_STRING_ELT(nms, 9, mkChar("dim_agein_12345"));
  SET_STRING_ELT(nms, 10, mkChar("dim_agein_123456"));
  SET_STRING_ELT(nms, 11, mkChar("dim_agein_2"));
  SET_STRING_ELT(nms, 12, mkChar("dim_agein_3"));
  SET_STRING_ELT(nms, 13, mkChar("dim_agein_4"));
  SET_STRING_ELT(nms, 14, mkChar("dim_agein_5"));
  SET_STRING_ELT(nms, 15, mkChar("dim_agein_6"));
  SET_STRING_ELT(nms, 16, mkChar("dim_agein_7"));
  SET_STRING_ELT(nms, 17, mkChar("dim_BB"));
  SET_STRING_ELT(nms, 18, mkChar("dim_BB_1"));
  SET_STRING_ELT(nms, 19, mkChar("dim_BB_2"));
  SET_STRING_ELT(nms, 20, mkChar("dim_birthrisk"));
  SET_STRING_ELT(nms, 21, mkChar("dim_bz"));
  SET_STRING_ELT(nms, 22, mkChar("dim_immigration"));
  SET_STRING_ELT(nms, 23, mkChar("dim_immigration_1"));
  SET_STRING_ELT(nms, 24, mkChar("dim_immigration_12"));
  SET_STRING_ELT(nms, 25, mkChar("dim_immigration_2"));
  SET_STRING_ELT(nms, 26, mkChar("dim_immigration_3"));
  SET_STRING_ELT(nms, 27, mkChar("dim_In"));
  SET_STRING_ELT(nms, 28, mkChar("dim_In_1"));
  SET_STRING_ELT(nms, 29, mkChar("dim_In_2"));
  SET_STRING_ELT(nms, 30, mkChar("dim_migr"));
  SET_STRING_ELT(nms, 31, mkChar("dim_migr_1"));
  SET_STRING_ELT(nms, 32, mkChar("dim_migr_12"));
  SET_STRING_ELT(nms, 33, mkChar("dim_migr_123"));
  SET_STRING_ELT(nms, 34, mkChar("dim_migr_1234"));
  SET_STRING_ELT(nms, 35, mkChar("dim_migr_12345"));
  SET_STRING_ELT(nms, 36, mkChar("dim_migr_123456"));
  SET_STRING_ELT(nms, 37, mkChar("dim_migr_2"));
  SET_STRING_ELT(nms, 38, mkChar("dim_migr_3"));
  SET_STRING_ELT(nms, 39, mkChar("dim_migr_4"));
  SET_STRING_ELT(nms, 40, mkChar("dim_migr_5"));
  SET_STRING_ELT(nms, 41, mkChar("dim_migr_6"));
  SET_STRING_ELT(nms, 42, mkChar("dim_migr_7"));
  SET_STRING_ELT(nms, 43, mkChar("dim_migrage"));
  SET_STRING_ELT(nms, 44, mkChar("dim_migragein"));
  SET_STRING_ELT(nms, 45, mkChar("dim_migragein_1"));
  SET_STRING_ELT(nms, 46, mkChar("dim_migragein_12"));
  SET_STRING_ELT(nms, 47, mkChar("dim_migragein_123"));
  SET_STRING_ELT(nms, 48, mkChar("dim_migragein_1234"));
  SET_STRING_ELT(nms, 49, mkChar("dim_migragein_12345"));
  SET_STRING_ELT(nms, 50, mkChar("dim_migragein_123456"));
  SET_STRING_ELT(nms, 51, mkChar("dim_migragein_2"));
  SET_STRING_ELT(nms, 52, mkChar("dim_migragein_3"));
  SET_STRING_ELT(nms, 53, mkChar("dim_migragein_4"));
  SET_STRING_ELT(nms, 54, mkChar("dim_migragein_5"));
  SET_STRING_ELT(nms, 55, mkChar("dim_migragein_6"));
  SET_STRING_ELT(nms, 56, mkChar("dim_migragein_7"));
  SET_STRING_ELT(nms, 57, mkChar("dim_migrageout"));
  SET_STRING_ELT(nms, 58, mkChar("dim_migrageout_1"));
  SET_STRING_ELT(nms, 59, mkChar("dim_migrageout_12"));
  SET_STRING_ELT(nms, 60, mkChar("dim_migrageout_123"));
  SET_STRING_ELT(nms, 61, mkChar("dim_migrageout_1234"));
  SET_STRING_ELT(nms, 62, mkChar("dim_migrageout_12345"));
  SET_STRING_ELT(nms, 63, mkChar("dim_migrageout_123456"));
  SET_STRING_ELT(nms, 64, mkChar("dim_migrageout_2"));
  SET_STRING_ELT(nms, 65, mkChar("dim_migrageout_3"));
  SET_STRING_ELT(nms, 66, mkChar("dim_migrageout_4"));
  SET_STRING_ELT(nms, 67, mkChar("dim_migrageout_5"));
  SET_STRING_ELT(nms, 68, mkChar("dim_migrageout_6"));
  SET_STRING_ELT(nms, 69, mkChar("dim_migrageout_7"));
  SET_STRING_ELT(nms, 70, mkChar("dim_N"));
  SET_STRING_ELT(nms, 71, mkChar("dim_N_1"));
  SET_STRING_ELT(nms, 72, mkChar("dim_N_12"));
  SET_STRING_ELT(nms, 73, mkChar("dim_N_123"));
  SET_STRING_ELT(nms, 74, mkChar("dim_N_1234"));
  SET_STRING_ELT(nms, 75, mkChar("dim_N_12345"));
  SET_STRING_ELT(nms, 76, mkChar("dim_N_123456"));
  SET_STRING_ELT(nms, 77, mkChar("dim_N_2"));
  SET_STRING_ELT(nms, 78, mkChar("dim_N_3"));
  SET_STRING_ELT(nms, 79, mkChar("dim_N_4"));
  SET_STRING_ELT(nms, 80, mkChar("dim_N_5"));
  SET_STRING_ELT(nms, 81, mkChar("dim_N_6"));
  SET_STRING_ELT(nms, 82, mkChar("dim_N_7"));
  SET_STRING_ELT(nms, 83, mkChar("dim_native"));
  SET_STRING_ELT(nms, 84, mkChar("dim_omega"));
  SET_STRING_ELT(nms, 85, mkChar("dim_omega_1"));
  SET_STRING_ELT(nms, 86, mkChar("dim_omega_2"));
  SET_STRING_ELT(nms, 87, mkChar("dim_Pmigr_nat"));
  SET_STRING_ELT(nms, 88, mkChar("dim_Pmigr_post"));
  SET_STRING_ELT(nms, 89, mkChar("dim_Pmigr_post_1"));
  SET_STRING_ELT(nms, 90, mkChar("dim_Pmigr_post_2"));
  SET_STRING_ELT(nms, 91, mkChar("dim_Pmigr_prot"));
  SET_STRING_ELT(nms, 92, mkChar("dim_Pmigr_prot_1"));
  SET_STRING_ELT(nms, 93, mkChar("dim_Pmigr_prot_2"));
  SET_STRING_ELT(nms, 94, mkChar("dim_Pmigr_risk"));
  SET_STRING_ELT(nms, 95, mkChar("dim_Pmigr_risk_1"));
  SET_STRING_ELT(nms, 96, mkChar("dim_Pmigr_risk_2"));
  SET_STRING_ELT(nms, 97, mkChar("dim_Pmigr_strain"));
  SET_STRING_ELT(nms, 98, mkChar("dim_Pmigr_strain_1"));
  SET_STRING_ELT(nms, 99, mkChar("dim_Pmigr_strain_2"));
  SET_STRING_ELT(nms, 100, mkChar("dim_popdat"));
  SET_STRING_ELT(nms, 101, mkChar("dim_popdat_1"));
  SET_STRING_ELT(nms, 102, mkChar("dim_popdat_12"));
  SET_STRING_ELT(nms, 103, mkChar("dim_popdat_2"));
  SET_STRING_ELT(nms, 104, mkChar("dim_popdat_3"));
  SET_STRING_ELT(nms, 105, mkChar("dim_popinit"));
  SET_STRING_ELT(nms, 106, mkChar("dim_popinit_1"));
  SET_STRING_ELT(nms, 107, mkChar("dim_popinit_12"));
  SET_STRING_ELT(nms, 108, mkChar("dim_popinit_123"));
  SET_STRING_ELT(nms, 109, mkChar("dim_popinit_1234"));
  SET_STRING_ELT(nms, 110, mkChar("dim_popinit_12345"));
  SET_STRING_ELT(nms, 111, mkChar("dim_popinit_123456"));
  SET_STRING_ELT(nms, 112, mkChar("dim_popinit_2"));
  SET_STRING_ELT(nms, 113, mkChar("dim_popinit_3"));
  SET_STRING_ELT(nms, 114, mkChar("dim_popinit_4"));
  SET_STRING_ELT(nms, 115, mkChar("dim_popinit_5"));
  SET_STRING_ELT(nms, 116, mkChar("dim_popinit_6"));
  SET_STRING_ELT(nms, 117, mkChar("dim_popinit_7"));
  SET_STRING_ELT(nms, 118, mkChar("dim_r"));
  SET_STRING_ELT(nms, 119, mkChar("dim_RiskChange"));
  SET_STRING_ELT(nms, 120, mkChar("dim_RiskChange_1"));
  SET_STRING_ELT(nms, 121, mkChar("dim_RiskChange_12"));
  SET_STRING_ELT(nms, 122, mkChar("dim_RiskChange_123"));
  SET_STRING_ELT(nms, 123, mkChar("dim_RiskChange_1234"));
  SET_STRING_ELT(nms, 124, mkChar("dim_RiskChange_12345"));
  SET_STRING_ELT(nms, 125, mkChar("dim_RiskChange_123456"));
  SET_STRING_ELT(nms, 126, mkChar("dim_RiskChange_2"));
  SET_STRING_ELT(nms, 127, mkChar("dim_RiskChange_3"));
  SET_STRING_ELT(nms, 128, mkChar("dim_RiskChange_4"));
  SET_STRING_ELT(nms, 129, mkChar("dim_RiskChange_5"));
  SET_STRING_ELT(nms, 130, mkChar("dim_RiskChange_6"));
  SET_STRING_ELT(nms, 131, mkChar("dim_RiskChange_7"));
  SET_STRING_ELT(nms, 132, mkChar("dim_RiskHazard"));
  SET_STRING_ELT(nms, 133, mkChar("dim_RiskHazard_1"));
  SET_STRING_ELT(nms, 134, mkChar("dim_RiskHazard_12"));
  SET_STRING_ELT(nms, 135, mkChar("dim_RiskHazard_2"));
  SET_STRING_ELT(nms, 136, mkChar("dim_RiskHazard_3"));
  SET_STRING_ELT(nms, 137, mkChar("dim_RiskHazardData"));
  SET_STRING_ELT(nms, 138, mkChar("dim_RiskHazardData_1"));
  SET_STRING_ELT(nms, 139, mkChar("dim_RiskHazardData_12"));
  SET_STRING_ELT(nms, 140, mkChar("dim_RiskHazardData_123"));
  SET_STRING_ELT(nms, 141, mkChar("dim_RiskHazardData_2"));
  SET_STRING_ELT(nms, 142, mkChar("dim_RiskHazardData_3"));
  SET_STRING_ELT(nms, 143, mkChar("dim_RiskHazardData_4"));
  SET_STRING_ELT(nms, 144, mkChar("dim_tbbottom"));
  SET_STRING_ELT(nms, 145, mkChar("dim_tbbottom_1"));
  SET_STRING_ELT(nms, 146, mkChar("dim_tbbottom_12"));
  SET_STRING_ELT(nms, 147, mkChar("dim_tbbottom_2"));
  SET_STRING_ELT(nms, 148, mkChar("dim_tbbottom_3"));
  SET_STRING_ELT(nms, 149, mkChar("dim_ttp"));
  SET_STRING_ELT(nms, 150, mkChar("immigration"));
  SET_STRING_ELT(nms, 151, mkChar("In"));
  SET_STRING_ELT(nms, 152, mkChar("initial_N"));
  SET_STRING_ELT(nms, 153, mkChar("interpolate_bz"));
  SET_STRING_ELT(nms, 154, mkChar("interpolate_In"));
  SET_STRING_ELT(nms, 155, mkChar("interpolate_omega"));
  SET_STRING_ELT(nms, 156, mkChar("interpolate_RiskHazard"));
  SET_STRING_ELT(nms, 157, mkChar("lttp"));
  SET_STRING_ELT(nms, 158, mkChar("migr"));
  SET_STRING_ELT(nms, 159, mkChar("migrage"));
  SET_STRING_ELT(nms, 160, mkChar("migragein"));
  SET_STRING_ELT(nms, 161, mkChar("migrageout"));
  SET_STRING_ELT(nms, 162, mkChar("nage"));
  SET_STRING_ELT(nms, 163, mkChar("native"));
  SET_STRING_ELT(nms, 164, mkChar("nnat"));
  SET_STRING_ELT(nms, 165, mkChar("npost"));
  SET_STRING_ELT(nms, 166, mkChar("nprot"));
  SET_STRING_ELT(nms, 167, mkChar("nrisk"));
  SET_STRING_ELT(nms, 168, mkChar("nstrain"));
  SET_STRING_ELT(nms, 169, mkChar("omega"));
  SET_STRING_ELT(nms, 170, mkChar("Pmigr_nat"));
  SET_STRING_ELT(nms, 171, mkChar("Pmigr_post"));
  SET_STRING_ELT(nms, 172, mkChar("Pmigr_prot"));
  SET_STRING_ELT(nms, 173, mkChar("Pmigr_risk"));
  SET_STRING_ELT(nms, 174, mkChar("Pmigr_strain"));
  SET_STRING_ELT(nms, 175, mkChar("popdat"));
  SET_STRING_ELT(nms, 176, mkChar("popinit"));
  SET_STRING_ELT(nms, 177, mkChar("r"));
  SET_STRING_ELT(nms, 178, mkChar("RiskChange"));
  SET_STRING_ELT(nms, 179, mkChar("RiskHazard"));
  SET_STRING_ELT(nms, 180, mkChar("RiskHazardData"));
  SET_STRING_ELT(nms, 181, mkChar("tbbottom"));
  SET_STRING_ELT(nms, 182, mkChar("ttp"));
  setAttrib(contents, R_NamesSymbol, nms);
  UNPROTECT(28);
  return contents;
}
SEXP ocaode_set_user(SEXP internal_p, SEXP user) {
  ocaode_internal *internal = ocaode_get_internal(internal_p, 1);
  internal->nage = user_get_scalar_int(user, "nage", internal->nage, NA_REAL, NA_REAL);
  internal->nnat = user_get_scalar_int(user, "nnat", internal->nnat, NA_REAL, NA_REAL);
  internal->npost = user_get_scalar_int(user, "npost", internal->npost, NA_REAL, NA_REAL);
  internal->nprot = user_get_scalar_int(user, "nprot", internal->nprot, NA_REAL, NA_REAL);
  internal->nrisk = user_get_scalar_int(user, "nrisk", internal->nrisk, NA_REAL, NA_REAL);
  internal->nstrain = user_get_scalar_int(user, "nstrain", internal->nstrain, NA_REAL, NA_REAL);
  internal->ttp = (double*) user_get_array_dim(user, false, internal->ttp, "ttp", 1, NA_REAL, NA_REAL, &internal->dim_ttp);
  internal->dim_agein_1 = internal->nage;
  internal->dim_agein_2 = 2;
  internal->dim_agein_3 = internal->nnat;
  internal->dim_agein_4 = internal->nrisk;
  internal->dim_agein_5 = internal->npost;
  internal->dim_agein_6 = internal->nstrain;
  internal->dim_agein_7 = internal->nprot;
  internal->dim_birthrisk = internal->nrisk;
  internal->dim_In_1 = internal->nage;
  internal->dim_In_2 = 2;
  internal->dim_migr_1 = internal->nage;
  internal->dim_migr_2 = 2;
  internal->dim_migr_3 = internal->nnat;
  internal->dim_migr_4 = internal->nrisk;
  internal->dim_migr_5 = internal->npost;
  internal->dim_migr_6 = internal->nstrain;
  internal->dim_migr_7 = internal->nprot;
  internal->dim_migrage = internal->nnat;
  internal->dim_migragein_1 = internal->nage;
  internal->dim_migragein_2 = 2;
  internal->dim_migragein_3 = internal->nnat;
  internal->dim_migragein_4 = internal->nrisk;
  internal->dim_migragein_5 = internal->npost;
  internal->dim_migragein_6 = internal->nstrain;
  internal->dim_migragein_7 = internal->nprot;
  internal->dim_migrageout_1 = internal->nage;
  internal->dim_migrageout_2 = 2;
  internal->dim_migrageout_3 = internal->nnat;
  internal->dim_migrageout_4 = internal->nrisk;
  internal->dim_migrageout_5 = internal->npost;
  internal->dim_migrageout_6 = internal->nstrain;
  internal->dim_migrageout_7 = internal->nprot;
  internal->dim_N_1 = internal->nage;
  internal->dim_N_2 = 2;
  internal->dim_N_3 = internal->nnat;
  internal->dim_N_4 = internal->nrisk;
  internal->dim_N_5 = internal->npost;
  internal->dim_N_6 = internal->nstrain;
  internal->dim_N_7 = internal->nprot;
  internal->dim_native = internal->nnat;
  internal->dim_omega_1 = internal->nage;
  internal->dim_omega_2 = 2;
  internal->dim_Pmigr_nat = internal->nnat;
  internal->dim_Pmigr_post_1 = 2;
  internal->dim_Pmigr_post_2 = internal->npost;
  internal->dim_Pmigr_prot_1 = 2;
  internal->dim_Pmigr_prot_2 = internal->nprot;
  internal->dim_Pmigr_risk_1 = 2;
  internal->dim_Pmigr_risk_2 = internal->nrisk;
  internal->dim_Pmigr_strain_1 = 2;
  internal->dim_Pmigr_strain_2 = internal->nstrain;
  internal->dim_popinit_1 = internal->nage;
  internal->dim_popinit_2 = 2;
  internal->dim_popinit_3 = internal->nnat;
  internal->dim_popinit_4 = internal->nrisk;
  internal->dim_popinit_5 = internal->npost;
  internal->dim_popinit_6 = internal->nstrain;
  internal->dim_popinit_7 = internal->nprot;
  internal->dim_r = internal->nage;
  internal->dim_RiskChange_1 = internal->nage;
  internal->dim_RiskChange_2 = 2;
  internal->dim_RiskChange_3 = internal->nnat;
  internal->dim_RiskChange_4 = internal->nrisk;
  internal->dim_RiskChange_5 = internal->npost;
  internal->dim_RiskChange_6 = internal->nstrain;
  internal->dim_RiskChange_7 = internal->nprot;
  internal->dim_RiskHazard_1 = internal->nage;
  internal->dim_RiskHazard_2 = 2;
  internal->dim_RiskHazard_3 = internal->nrisk;
  internal->dim_tbbottom_1 = internal->npost;
  internal->dim_tbbottom_2 = internal->nstrain;
  internal->dim_tbbottom_3 = internal->nprot;
  R_Free(internal->native);
  internal->native = (double*) R_Calloc(internal->dim_native, double);
  R_Free(internal->Pmigr_nat);
  internal->Pmigr_nat = (double*) R_Calloc(internal->dim_Pmigr_nat, double);
  internal->birthrisk = (double*) user_get_array(user, false, internal->birthrisk, "birthrisk", NA_REAL, NA_REAL, 1, internal->dim_birthrisk);
  internal->dim_agein = internal->dim_agein_1 * internal->dim_agein_2 * internal->dim_agein_3 * internal->dim_agein_4 * internal->dim_agein_5 * internal->dim_agein_6 * internal->dim_agein_7;
  internal->dim_agein_12 = internal->dim_agein_1 * internal->dim_agein_2;
  internal->dim_agein_123 = internal->dim_agein_1 * internal->dim_agein_2 * internal->dim_agein_3;
  internal->dim_agein_1234 = internal->dim_agein_1 * internal->dim_agein_2 * internal->dim_agein_3 * internal->dim_agein_4;
  internal->dim_agein_12345 = internal->dim_agein_1 * internal->dim_agein_2 * internal->dim_agein_3 * internal->dim_agein_4 * internal->dim_agein_5;
  internal->dim_agein_123456 = internal->dim_agein_1 * internal->dim_agein_2 * internal->dim_agein_3 * internal->dim_agein_4 * internal->dim_agein_5 * internal->dim_agein_6;
  internal->dim_In = internal->dim_In_1 * internal->dim_In_2;
  internal->dim_migr = internal->dim_migr_1 * internal->dim_migr_2 * internal->dim_migr_3 * internal->dim_migr_4 * internal->dim_migr_5 * internal->dim_migr_6 * internal->dim_migr_7;
  internal->dim_migr_12 = internal->dim_migr_1 * internal->dim_migr_2;
  internal->dim_migr_123 = internal->dim_migr_1 * internal->dim_migr_2 * internal->dim_migr_3;
  internal->dim_migr_1234 = internal->dim_migr_1 * internal->dim_migr_2 * internal->dim_migr_3 * internal->dim_migr_4;
  internal->dim_migr_12345 = internal->dim_migr_1 * internal->dim_migr_2 * internal->dim_migr_3 * internal->dim_migr_4 * internal->dim_migr_5;
  internal->dim_migr_123456 = internal->dim_migr_1 * internal->dim_migr_2 * internal->dim_migr_3 * internal->dim_migr_4 * internal->dim_migr_5 * internal->dim_migr_6;
  internal->dim_migragein = internal->dim_migragein_1 * internal->dim_migragein_2 * internal->dim_migragein_3 * internal->dim_migragein_4 * internal->dim_migragein_5 * internal->dim_migragein_6 * internal->dim_migragein_7;
  internal->dim_migragein_12 = internal->dim_migragein_1 * internal->dim_migragein_2;
  internal->dim_migragein_123 = internal->dim_migragein_1 * internal->dim_migragein_2 * internal->dim_migragein_3;
  internal->dim_migragein_1234 = internal->dim_migragein_1 * internal->dim_migragein_2 * internal->dim_migragein_3 * internal->dim_migragein_4;
  internal->dim_migragein_12345 = internal->dim_migragein_1 * internal->dim_migragein_2 * internal->dim_migragein_3 * internal->dim_migragein_4 * internal->dim_migragein_5;
  internal->dim_migragein_123456 = internal->dim_migragein_1 * internal->dim_migragein_2 * internal->dim_migragein_3 * internal->dim_migragein_4 * internal->dim_migragein_5 * internal->dim_migragein_6;
  internal->dim_migrageout = internal->dim_migrageout_1 * internal->dim_migrageout_2 * internal->dim_migrageout_3 * internal->dim_migrageout_4 * internal->dim_migrageout_5 * internal->dim_migrageout_6 * internal->dim_migrageout_7;
  internal->dim_migrageout_12 = internal->dim_migrageout_1 * internal->dim_migrageout_2;
  internal->dim_migrageout_123 = internal->dim_migrageout_1 * internal->dim_migrageout_2 * internal->dim_migrageout_3;
  internal->dim_migrageout_1234 = internal->dim_migrageout_1 * internal->dim_migrageout_2 * internal->dim_migrageout_3 * internal->dim_migrageout_4;
  internal->dim_migrageout_12345 = internal->dim_migrageout_1 * internal->dim_migrageout_2 * internal->dim_migrageout_3 * internal->dim_migrageout_4 * internal->dim_migrageout_5;
  internal->dim_migrageout_123456 = internal->dim_migrageout_1 * internal->dim_migrageout_2 * internal->dim_migrageout_3 * internal->dim_migrageout_4 * internal->dim_migrageout_5 * internal->dim_migrageout_6;
  internal->dim_N = internal->dim_N_1 * internal->dim_N_2 * internal->dim_N_3 * internal->dim_N_4 * internal->dim_N_5 * internal->dim_N_6 * internal->dim_N_7;
  internal->dim_N_12 = internal->dim_N_1 * internal->dim_N_2;
  internal->dim_N_123 = internal->dim_N_1 * internal->dim_N_2 * internal->dim_N_3;
  internal->dim_N_1234 = internal->dim_N_1 * internal->dim_N_2 * internal->dim_N_3 * internal->dim_N_4;
  internal->dim_N_12345 = internal->dim_N_1 * internal->dim_N_2 * internal->dim_N_3 * internal->dim_N_4 * internal->dim_N_5;
  internal->dim_N_123456 = internal->dim_N_1 * internal->dim_N_2 * internal->dim_N_3 * internal->dim_N_4 * internal->dim_N_5 * internal->dim_N_6;
  internal->dim_omega = internal->dim_omega_1 * internal->dim_omega_2;
  internal->dim_Pmigr_post = internal->dim_Pmigr_post_1 * internal->dim_Pmigr_post_2;
  internal->dim_Pmigr_prot = internal->dim_Pmigr_prot_1 * internal->dim_Pmigr_prot_2;
  internal->dim_Pmigr_risk = internal->dim_Pmigr_risk_1 * internal->dim_Pmigr_risk_2;
  internal->dim_Pmigr_strain = internal->dim_Pmigr_strain_1 * internal->dim_Pmigr_strain_2;
  internal->dim_popinit = internal->dim_popinit_1 * internal->dim_popinit_2 * internal->dim_popinit_3 * internal->dim_popinit_4 * internal->dim_popinit_5 * internal->dim_popinit_6 * internal->dim_popinit_7;
  internal->dim_popinit_12 = internal->dim_popinit_1 * internal->dim_popinit_2;
  internal->dim_popinit_123 = internal->dim_popinit_1 * internal->dim_popinit_2 * internal->dim_popinit_3;
  internal->dim_popinit_1234 = internal->dim_popinit_1 * internal->dim_popinit_2 * internal->dim_popinit_3 * internal->dim_popinit_4;
  internal->dim_popinit_12345 = internal->dim_popinit_1 * internal->dim_popinit_2 * internal->dim_popinit_3 * internal->dim_popinit_4 * internal->dim_popinit_5;
  internal->dim_popinit_123456 = internal->dim_popinit_1 * internal->dim_popinit_2 * internal->dim_popinit_3 * internal->dim_popinit_4 * internal->dim_popinit_5 * internal->dim_popinit_6;
  internal->dim_RiskChange = internal->dim_RiskChange_1 * internal->dim_RiskChange_2 * internal->dim_RiskChange_3 * internal->dim_RiskChange_4 * internal->dim_RiskChange_5 * internal->dim_RiskChange_6 * internal->dim_RiskChange_7;
  internal->dim_RiskChange_12 = internal->dim_RiskChange_1 * internal->dim_RiskChange_2;
  internal->dim_RiskChange_123 = internal->dim_RiskChange_1 * internal->dim_RiskChange_2 * internal->dim_RiskChange_3;
  internal->dim_RiskChange_1234 = internal->dim_RiskChange_1 * internal->dim_RiskChange_2 * internal->dim_RiskChange_3 * internal->dim_RiskChange_4;
  internal->dim_RiskChange_12345 = internal->dim_RiskChange_1 * internal->dim_RiskChange_2 * internal->dim_RiskChange_3 * internal->dim_RiskChange_4 * internal->dim_RiskChange_5;
  internal->dim_RiskChange_123456 = internal->dim_RiskChange_1 * internal->dim_RiskChange_2 * internal->dim_RiskChange_3 * internal->dim_RiskChange_4 * internal->dim_RiskChange_5 * internal->dim_RiskChange_6;
  internal->dim_RiskHazard = internal->dim_RiskHazard_1 * internal->dim_RiskHazard_2 * internal->dim_RiskHazard_3;
  internal->dim_RiskHazard_12 = internal->dim_RiskHazard_1 * internal->dim_RiskHazard_2;
  internal->dim_tbbottom = internal->dim_tbbottom_1 * internal->dim_tbbottom_2 * internal->dim_tbbottom_3;
  internal->dim_tbbottom_12 = internal->dim_tbbottom_1 * internal->dim_tbbottom_2;
  internal->lttp = internal->dim_ttp;
  internal->migrage = (double*) user_get_array(user, false, internal->migrage, "migrage", NA_REAL, NA_REAL, 1, internal->dim_migrage);
  internal->r = (double*) user_get_array(user, false, internal->r, "r", NA_REAL, NA_REAL, 1, internal->dim_r);
  R_Free(internal->agein);
  internal->agein = (double*) R_Calloc(internal->dim_agein, double);
  R_Free(internal->In);
  internal->In = (double*) R_Calloc(internal->dim_In, double);
  R_Free(internal->initial_N);
  internal->initial_N = (double*) R_Calloc(internal->dim_N, double);
  R_Free(internal->migr);
  internal->migr = (double*) R_Calloc(internal->dim_migr, double);
  R_Free(internal->migragein);
  internal->migragein = (double*) R_Calloc(internal->dim_migragein, double);
  R_Free(internal->migrageout);
  internal->migrageout = (double*) R_Calloc(internal->dim_migrageout, double);
  R_Free(internal->omega);
  internal->omega = (double*) R_Calloc(internal->dim_omega, double);
  R_Free(internal->RiskChange);
  internal->RiskChange = (double*) R_Calloc(internal->dim_RiskChange, double);
  R_Free(internal->RiskHazard);
  internal->RiskHazard = (double*) R_Calloc(internal->dim_RiskHazard, double);
  R_Free(internal->tbbottom);
  internal->tbbottom = (double*) R_Calloc(internal->dim_tbbottom, double);
  internal->dim_BB_1 = internal->lttp;
  internal->dim_BB_2 = 2;
  internal->dim_immigration_1 = internal->lttp;
  internal->dim_immigration_2 = internal->nage;
  internal->dim_immigration_3 = 2;
  internal->dim_popdat_1 = internal->lttp;
  internal->dim_popdat_2 = internal->nage;
  internal->dim_popdat_3 = 2;
  internal->dim_RiskHazardData_1 = internal->lttp;
  internal->dim_RiskHazardData_2 = internal->nage;
  internal->dim_RiskHazardData_3 = 2;
  internal->dim_RiskHazardData_4 = internal->nrisk;
  {
     int i = 1;
     internal->native[i - 1] = 1;
  }
  for (int i = 2; i <= internal->nnat; ++i) {
    internal->native[i - 1] = 0;
  }
  for (int i = 1; i <= internal->nnat; ++i) {
    internal->Pmigr_nat[i - 1] = (i == 2 ? 1 : 0);
  }
  internal->Pmigr_post = (double*) user_get_array(user, false, internal->Pmigr_post, "Pmigr_post", NA_REAL, NA_REAL, 2, internal->dim_Pmigr_post_1, internal->dim_Pmigr_post_2);
  internal->Pmigr_prot = (double*) user_get_array(user, false, internal->Pmigr_prot, "Pmigr_prot", NA_REAL, NA_REAL, 2, internal->dim_Pmigr_prot_1, internal->dim_Pmigr_prot_2);
  internal->Pmigr_risk = (double*) user_get_array(user, false, internal->Pmigr_risk, "Pmigr_risk", NA_REAL, NA_REAL, 2, internal->dim_Pmigr_risk_1, internal->dim_Pmigr_risk_2);
  internal->Pmigr_strain = (double*) user_get_array(user, false, internal->Pmigr_strain, "Pmigr_strain", NA_REAL, NA_REAL, 2, internal->dim_Pmigr_strain_1, internal->dim_Pmigr_strain_2);
  internal->popinit = (double*) user_get_array(user, false, internal->popinit, "popinit", NA_REAL, NA_REAL, 7, internal->dim_popinit_1, internal->dim_popinit_2, internal->dim_popinit_3, internal->dim_popinit_4, internal->dim_popinit_5, internal->dim_popinit_6, internal->dim_popinit_7);
  internal->dim_BB = internal->dim_BB_1 * internal->dim_BB_2;
  internal->dim_immigration = internal->dim_immigration_1 * internal->dim_immigration_2 * internal->dim_immigration_3;
  internal->dim_immigration_12 = internal->dim_immigration_1 * internal->dim_immigration_2;
  internal->dim_popdat = internal->dim_popdat_1 * internal->dim_popdat_2 * internal->dim_popdat_3;
  internal->dim_popdat_12 = internal->dim_popdat_1 * internal->dim_popdat_2;
  internal->dim_RiskHazardData = internal->dim_RiskHazardData_1 * internal->dim_RiskHazardData_2 * internal->dim_RiskHazardData_3 * internal->dim_RiskHazardData_4;
  internal->dim_RiskHazardData_12 = internal->dim_RiskHazardData_1 * internal->dim_RiskHazardData_2;
  internal->dim_RiskHazardData_123 = internal->dim_RiskHazardData_1 * internal->dim_RiskHazardData_2 * internal->dim_RiskHazardData_3;
  for (int i = 1; i <= internal->nage; ++i) {
    for (int j = 1; j <= 2; ++j) {
      for (int k = 1; k <= internal->nnat; ++k) {
        for (int l = 1; l <= internal->nrisk; ++l) {
          for (int i5 = 1; i5 <= internal->npost; ++i5) {
            for (int i6 = 1; i6 <= internal->nstrain; ++i6) {
              for (int i7 = 1; i7 <= internal->nprot; ++i7) {
                internal->initial_N[i - 1 + internal->dim_N_1 * (j - 1) + internal->dim_N_12 * (k - 1) + internal->dim_N_123 * (l - 1) + internal->dim_N_1234 * (i5 - 1) + internal->dim_N_12345 * (i6 - 1) + internal->dim_N_123456 * (i7 - 1)] = internal->popinit[internal->dim_popinit_123456 * (i7 - 1) + internal->dim_popinit_12345 * (i6 - 1) + internal->dim_popinit_1234 * (i5 - 1) + internal->dim_popinit_123 * (l - 1) + internal->dim_popinit_12 * (k - 1) + internal->dim_popinit_1 * (j - 1) + i - 1];
              }
            }
          }
        }
      }
    }
  }
  for (int i = 1; i <= internal->npost; ++i) {
    for (int j = 1; j <= internal->nstrain; ++j) {
      for (int k = 1; k <= internal->nprot; ++k) {
        internal->tbbottom[i - 1 + internal->dim_tbbottom_1 * (j - 1) + internal->dim_tbbottom_12 * (k - 1)] = 0;
      }
    }
  }
  {
     int i = 1;
     int j = 1;
     int k = 1;
     internal->tbbottom[i - 1 + internal->dim_tbbottom_1 * (j - 1) + internal->dim_tbbottom_12 * (k - 1)] = 1;
  }
  internal->BB = (double*) user_get_array(user, false, internal->BB, "BB", NA_REAL, NA_REAL, 2, internal->dim_BB_1, internal->dim_BB_2);
  internal->immigration = (double*) user_get_array(user, false, internal->immigration, "immigration", NA_REAL, NA_REAL, 3, internal->dim_immigration_1, internal->dim_immigration_2, internal->dim_immigration_3);
  internal->popdat = (double*) user_get_array(user, false, internal->popdat, "popdat", NA_REAL, NA_REAL, 3, internal->dim_popdat_1, internal->dim_popdat_2, internal->dim_popdat_3);
  internal->RiskHazardData = (double*) user_get_array(user, false, internal->RiskHazardData, "RiskHazardData", NA_REAL, NA_REAL, 4, internal->dim_RiskHazardData_1, internal->dim_RiskHazardData_2, internal->dim_RiskHazardData_3, internal->dim_RiskHazardData_4);
  interpolate_check_y(internal->dim_ttp, internal->dim_BB_1, 1, "BB", "bz");
  interpolate_check_y(internal->dim_bz, internal->dim_BB_2, 2, "BB", "bz");
  cinterpolate_free(internal->interpolate_bz);
  internal->interpolate_bz = cinterpolate_alloc("linear", internal->dim_ttp, internal->dim_bz, internal->ttp, internal->BB, true, false);
  interpolate_check_y(internal->dim_ttp, internal->dim_immigration_1, 1, "immigration", "In");
  interpolate_check_y(internal->dim_In_1, internal->dim_immigration_2, 2, "immigration", "In");
  interpolate_check_y(internal->dim_In_2, internal->dim_immigration_3, 3, "immigration", "In");
  cinterpolate_free(internal->interpolate_In);
  internal->interpolate_In = cinterpolate_alloc("linear", internal->dim_ttp, internal->dim_In, internal->ttp, internal->immigration, true, false);
  interpolate_check_y(internal->dim_ttp, internal->dim_popdat_1, 1, "popdat", "omega");
  interpolate_check_y(internal->dim_omega_1, internal->dim_popdat_2, 2, "popdat", "omega");
  interpolate_check_y(internal->dim_omega_2, internal->dim_popdat_3, 3, "popdat", "omega");
  cinterpolate_free(internal->interpolate_omega);
  internal->interpolate_omega = cinterpolate_alloc("linear", internal->dim_ttp, internal->dim_omega, internal->ttp, internal->popdat, true, false);
  interpolate_check_y(internal->dim_ttp, internal->dim_RiskHazardData_1, 1, "RiskHazardData", "RiskHazard");
  interpolate_check_y(internal->dim_RiskHazard_1, internal->dim_RiskHazardData_2, 2, "RiskHazardData", "RiskHazard");
  interpolate_check_y(internal->dim_RiskHazard_2, internal->dim_RiskHazardData_3, 3, "RiskHazardData", "RiskHazard");
  interpolate_check_y(internal->dim_RiskHazard_3, internal->dim_RiskHazardData_4, 4, "RiskHazardData", "RiskHazard");
  cinterpolate_free(internal->interpolate_RiskHazard);
  internal->interpolate_RiskHazard = cinterpolate_alloc("linear", internal->dim_ttp, internal->dim_RiskHazard, internal->ttp, internal->RiskHazardData, true, false);
  return R_NilValue;
}
SEXP ocaode_set_initial(SEXP internal_p, SEXP t_ptr, SEXP state_ptr, SEXP ocaode_use_dde_ptr) {
  return R_NilValue;
}
SEXP ocaode_metadata(SEXP internal_p) {
  ocaode_internal *internal = ocaode_get_internal(internal_p, 1);
  SEXP ret = PROTECT(allocVector(VECSXP, 4));
  SEXP nms = PROTECT(allocVector(STRSXP, 4));
  SET_STRING_ELT(nms, 0, mkChar("variable_order"));
  SET_STRING_ELT(nms, 1, mkChar("output_order"));
  SET_STRING_ELT(nms, 2, mkChar("n_out"));
  SET_STRING_ELT(nms, 3, mkChar("interpolate_t"));
  setAttrib(ret, R_NamesSymbol, nms);
  SEXP variable_length = PROTECT(allocVector(VECSXP, 1));
  SEXP variable_names = PROTECT(allocVector(STRSXP, 1));
  setAttrib(variable_length, R_NamesSymbol, variable_names);
  SET_VECTOR_ELT(variable_length, 0, allocVector(INTSXP, 7));
  int * dim_N = INTEGER(VECTOR_ELT(variable_length, 0));
  dim_N[0] = internal->dim_N_1;
  dim_N[1] = internal->dim_N_2;
  dim_N[2] = internal->dim_N_3;
  dim_N[3] = internal->dim_N_4;
  dim_N[4] = internal->dim_N_5;
  dim_N[5] = internal->dim_N_6;
  dim_N[6] = internal->dim_N_7;
  SET_STRING_ELT(variable_names, 0, mkChar("N"));
  SET_VECTOR_ELT(ret, 0, variable_length);
  UNPROTECT(2);
  SET_VECTOR_ELT(ret, 1, R_NilValue);
  SET_VECTOR_ELT(ret, 2, ScalarInteger(0));
  SEXP interpolate_t = PROTECT(allocVector(VECSXP, 3));
  SEXP interpolate_t_nms = PROTECT(allocVector(STRSXP, 3));
  setAttrib(interpolate_t, R_NamesSymbol, interpolate_t_nms);
  SET_VECTOR_ELT(interpolate_t, 0, ScalarReal(internal->ttp[0]));
  SET_VECTOR_ELT(interpolate_t, 1, ScalarReal(internal->ttp[internal->dim_ttp - 1]));
  SET_STRING_ELT(interpolate_t_nms, 0, mkChar("min"));
  SET_STRING_ELT(interpolate_t_nms, 1, mkChar("max"));
  SET_VECTOR_ELT(ret, 3, interpolate_t);
  UNPROTECT(2);
  UNPROTECT(2);
  return ret;
}
SEXP ocaode_initial_conditions(SEXP internal_p, SEXP t_ptr) {
  ocaode_internal *internal = ocaode_get_internal(internal_p, 1);
  SEXP r_state = PROTECT(allocVector(REALSXP, internal->dim_N));
  double * state = REAL(r_state);
  memcpy(state + 0, internal->initial_N, internal->dim_N * sizeof(double));
  UNPROTECT(1);
  return r_state;
}
void ocaode_rhs(ocaode_internal* internal, double t, double * state, double * dstatedt, double * output) {
  double * N = state + 0;
  for (int i = 1; i <= internal->nage; ++i) {
    for (int j = 1; j <= 2; ++j) {
      for (int k = 1; k <= internal->nnat; ++k) {
        for (int l = 1; l <= internal->nrisk; ++l) {
          for (int i5 = 1; i5 <= internal->npost; ++i5) {
            for (int i6 = 1; i6 <= internal->nstrain; ++i6) {
              for (int i7 = 1; i7 <= internal->nprot; ++i7) {
                internal->migragein[i - 1 + internal->dim_migragein_1 * (j - 1) + internal->dim_migragein_12 * (k - 1) + internal->dim_migragein_123 * (l - 1) + internal->dim_migragein_1234 * (i5 - 1) + internal->dim_migragein_12345 * (i6 - 1) + internal->dim_migragein_123456 * (i7 - 1)] = (k > 2 ? N[internal->dim_N_123456 * (i7 - 1) + internal->dim_N_12345 * (i6 - 1) + internal->dim_N_1234 * (i5 - 1) + internal->dim_N_123 * (l - 1) + internal->dim_N_12 * (k - 1 - 1) + internal->dim_N_1 * (j - 1) + i - 1] * internal->migrage[k - 1 - 1] : 0);
              }
            }
          }
        }
      }
    }
  }
  for (int i = 1; i <= internal->nage; ++i) {
    for (int j = 1; j <= 2; ++j) {
      for (int k = 1; k <= internal->nnat; ++k) {
        for (int l = 1; l <= internal->nrisk; ++l) {
          for (int i5 = 1; i5 <= internal->npost; ++i5) {
            for (int i6 = 1; i6 <= internal->nstrain; ++i6) {
              for (int i7 = 1; i7 <= internal->nprot; ++i7) {
                internal->migrageout[i - 1 + internal->dim_migrageout_1 * (j - 1) + internal->dim_migrageout_12 * (k - 1) + internal->dim_migrageout_123 * (l - 1) + internal->dim_migrageout_1234 * (i5 - 1) + internal->dim_migrageout_12345 * (i6 - 1) + internal->dim_migrageout_123456 * (i7 - 1)] = (k > 1 && k < internal->nnat ? N[internal->dim_N_123456 * (i7 - 1) + internal->dim_N_12345 * (i6 - 1) + internal->dim_N_1234 * (i5 - 1) + internal->dim_N_123 * (l - 1) + internal->dim_N_12 * (k - 1) + internal->dim_N_1 * (j - 1) + i - 1] * internal->migrage[k - 1] : 0);
              }
            }
          }
        }
      }
    }
  }
  cinterpolate_eval(t, internal->interpolate_bz, internal->bz);
  cinterpolate_eval(t, internal->interpolate_In, internal->In);
  cinterpolate_eval(t, internal->interpolate_omega, internal->omega);
  cinterpolate_eval(t, internal->interpolate_RiskHazard, internal->RiskHazard);
  for (int i = 1; i <= internal->nage; ++i) {
    for (int j = 1; j <= 2; ++j) {
      for (int k = 1; k <= internal->nnat; ++k) {
        for (int l = 1; l <= internal->nrisk; ++l) {
          for (int i5 = 1; i5 <= internal->npost; ++i5) {
            for (int i6 = 1; i6 <= internal->nstrain; ++i6) {
              for (int i7 = 1; i7 <= internal->nprot; ++i7) {
                internal->agein[i - 1 + internal->dim_agein_1 * (j - 1) + internal->dim_agein_12 * (k - 1) + internal->dim_agein_123 * (l - 1) + internal->dim_agein_1234 * (i5 - 1) + internal->dim_agein_12345 * (i6 - 1) + internal->dim_agein_123456 * (i7 - 1)] = (i > 1 ? internal->r[i - 1 - 1] * N[internal->dim_N_123456 * (i7 - 1) + internal->dim_N_12345 * (i6 - 1) + internal->dim_N_1234 * (i5 - 1) + internal->dim_N_123 * (l - 1) + internal->dim_N_12 * (k - 1) + internal->dim_N_1 * (j - 1) + i - 1 - 1] : internal->bz[j - 1] * internal->native[k - 1] * internal->birthrisk[l - 1] * internal->tbbottom[internal->dim_tbbottom_12 * (i7 - 1) + internal->dim_tbbottom_1 * (i6 - 1) + i5 - 1]);
              }
            }
          }
        }
      }
    }
  }
  for (int i = 1; i <= internal->nage; ++i) {
    for (int j = 1; j <= 2; ++j) {
      for (int k = 1; k <= internal->nnat; ++k) {
        for (int l = 1; l <= internal->nrisk; ++l) {
          for (int i5 = 1; i5 <= internal->npost; ++i5) {
            for (int i6 = 1; i6 <= internal->nstrain; ++i6) {
              for (int i7 = 1; i7 <= internal->nprot; ++i7) {
                internal->migr[i - 1 + internal->dim_migr_1 * (j - 1) + internal->dim_migr_12 * (k - 1) + internal->dim_migr_123 * (l - 1) + internal->dim_migr_1234 * (i5 - 1) + internal->dim_migr_12345 * (i6 - 1) + internal->dim_migr_123456 * (i7 - 1)] = internal->In[internal->dim_In_1 * (j - 1) + i - 1] * internal->Pmigr_nat[k - 1] * internal->Pmigr_risk[internal->dim_Pmigr_risk_1 * (l - 1) + j - 1] * internal->Pmigr_post[internal->dim_Pmigr_post_1 * (i5 - 1) + j - 1] * internal->Pmigr_strain[internal->dim_Pmigr_strain_1 * (i6 - 1) + j - 1] * internal->Pmigr_prot[internal->dim_Pmigr_prot_1 * (i7 - 1) + j - 1];
              }
            }
          }
        }
      }
    }
  }
  for (int i = 1; i <= internal->nage; ++i) {
    for (int j = 1; j <= 2; ++j) {
      for (int k = 1; k <= internal->nnat; ++k) {
        for (int l = 1; l <= internal->nrisk; ++l) {
          for (int i5 = 1; i5 <= internal->npost; ++i5) {
            for (int i6 = 1; i6 <= internal->nstrain; ++i6) {
              for (int i7 = 1; i7 <= internal->nprot; ++i7) {
                internal->RiskChange[i - 1 + internal->dim_RiskChange_1 * (j - 1) + internal->dim_RiskChange_12 * (k - 1) + internal->dim_RiskChange_123 * (l - 1) + internal->dim_RiskChange_1234 * (i5 - 1) + internal->dim_RiskChange_12345 * (i6 - 1) + internal->dim_RiskChange_123456 * (i7 - 1)] = (l > 1 ? internal->RiskHazard[internal->dim_RiskHazard_12 * (l - 1 - 1) + internal->dim_RiskHazard_1 * (j - 1) + i - 1] * N[internal->dim_N_123456 * (i7 - 1) + internal->dim_N_12345 * (i6 - 1) + internal->dim_N_1234 * (i5 - 1) + internal->dim_N_123 * (l - 1 - 1) + internal->dim_N_12 * (k - 1) + internal->dim_N_1 * (j - 1) + i - 1] - internal->RiskHazard[internal->dim_RiskHazard_12 * (l - 1) + internal->dim_RiskHazard_1 * (j - 1) + i - 1] * N[internal->dim_N_123456 * (i7 - 1) + internal->dim_N_12345 * (i6 - 1) + internal->dim_N_1234 * (i5 - 1) + internal->dim_N_123 * (l - 1) + internal->dim_N_12 * (k - 1) + internal->dim_N_1 * (j - 1) + i - 1] : -(internal->RiskHazard[internal->dim_RiskHazard_12 * (l - 1) + internal->dim_RiskHazard_1 * (j - 1) + i - 1]) * N[internal->dim_N_123456 * (i7 - 1) + internal->dim_N_12345 * (i6 - 1) + internal->dim_N_1234 * (i5 - 1) + internal->dim_N_123 * (l - 1) + internal->dim_N_12 * (k - 1) + internal->dim_N_1 * (j - 1) + i - 1]);
              }
            }
          }
        }
      }
    }
  }
  for (int i = 1; i <= internal->nage; ++i) {
    for (int j = 1; j <= 2; ++j) {
      for (int k = 1; k <= internal->nnat; ++k) {
        for (int l = 1; l <= internal->nrisk; ++l) {
          for (int i5 = 1; i5 <= internal->npost; ++i5) {
            for (int i6 = 1; i6 <= internal->nstrain; ++i6) {
              for (int i7 = 1; i7 <= internal->nprot; ++i7) {
                dstatedt[0 + i - 1 + internal->dim_N_1 * (j - 1) + internal->dim_N_12 * (k - 1) + internal->dim_N_123 * (l - 1) + internal->dim_N_1234 * (i5 - 1) + internal->dim_N_12345 * (i6 - 1) + internal->dim_N_123456 * (i7 - 1)] = internal->agein[internal->dim_agein_123456 * (i7 - 1) + internal->dim_agein_12345 * (i6 - 1) + internal->dim_agein_1234 * (i5 - 1) + internal->dim_agein_123 * (l - 1) + internal->dim_agein_12 * (k - 1) + internal->dim_agein_1 * (j - 1) + i - 1] - internal->omega[internal->dim_omega_1 * (j - 1) + i - 1] * N[internal->dim_N_123456 * (i7 - 1) + internal->dim_N_12345 * (i6 - 1) + internal->dim_N_1234 * (i5 - 1) + internal->dim_N_123 * (l - 1) + internal->dim_N_12 * (k - 1) + internal->dim_N_1 * (j - 1) + i - 1] + internal->migr[internal->dim_migr_123456 * (i7 - 1) + internal->dim_migr_12345 * (i6 - 1) + internal->dim_migr_1234 * (i5 - 1) + internal->dim_migr_123 * (l - 1) + internal->dim_migr_12 * (k - 1) + internal->dim_migr_1 * (j - 1) + i - 1] + internal->migragein[internal->dim_migragein_123456 * (i7 - 1) + internal->dim_migragein_12345 * (i6 - 1) + internal->dim_migragein_1234 * (i5 - 1) + internal->dim_migragein_123 * (l - 1) + internal->dim_migragein_12 * (k - 1) + internal->dim_migragein_1 * (j - 1) + i - 1] - internal->migrageout[internal->dim_migrageout_123456 * (i7 - 1) + internal->dim_migrageout_12345 * (i6 - 1) + internal->dim_migrageout_1234 * (i5 - 1) + internal->dim_migrageout_123 * (l - 1) + internal->dim_migrageout_12 * (k - 1) + internal->dim_migrageout_1 * (j - 1) + i - 1] + internal->RiskChange[internal->dim_RiskChange_123456 * (i7 - 1) + internal->dim_RiskChange_12345 * (i6 - 1) + internal->dim_RiskChange_1234 * (i5 - 1) + internal->dim_RiskChange_123 * (l - 1) + internal->dim_RiskChange_12 * (k - 1) + internal->dim_RiskChange_1 * (j - 1) + i - 1];
              }
            }
          }
        }
      }
    }
  }
}
void ocaode_rhs_dde(size_t neq, double t, double * state, double * dstatedt, void * internal) {
  ocaode_rhs((ocaode_internal*)internal, t, state, dstatedt, NULL);
}
void ocaode_rhs_desolve(int * neq, double * t, double * state, double * dstatedt, double * output, int * np) {
  ocaode_rhs(ocaode_internal_ds, *t, state, dstatedt, output);
}
SEXP ocaode_rhs_r(SEXP internal_p, SEXP t, SEXP state) {
  SEXP dstatedt = PROTECT(allocVector(REALSXP, LENGTH(state)));
  ocaode_internal *internal = ocaode_get_internal(internal_p, 1);
  double *output = NULL;
  ocaode_rhs(internal, scalar_real(t, "t"), REAL(state), REAL(dstatedt), output);
  UNPROTECT(1);
  return dstatedt;
}
double user_get_scalar_double(SEXP user, const char *name,
                              double default_value, double min, double max) {
  double ret = default_value;
  SEXP el = user_list_element(user, name);
  if (el != R_NilValue) {
    if (length(el) != 1) {
      Rf_error("Expected a scalar numeric for '%s'", name);
    }
    if (TYPEOF(el) == REALSXP) {
      ret = REAL(el)[0];
    } else if (TYPEOF(el) == INTSXP) {
      ret = INTEGER(el)[0];
    } else {
      Rf_error("Expected a numeric value for '%s'", name);
    }
  }
  if (ISNA(ret)) {
    Rf_error("Expected a value for '%s'", name);
  }
  user_check_values_double(&ret, 1, min, max, name);
  return ret;
}
int user_get_scalar_int(SEXP user, const char *name,
                        int default_value, double min, double max) {
  int ret = default_value;
  SEXP el = user_list_element(user, name);
  if (el != R_NilValue) {
    if (length(el) != 1) {
      Rf_error("Expected scalar integer for '%s'", name);
    }
    if (TYPEOF(el) == REALSXP) {
      double tmp = REAL(el)[0];
      if (fabs(tmp - round(tmp)) > 2e-8) {
        Rf_error("Expected '%s' to be integer-like", name);
      }
    }
    ret = INTEGER(coerceVector(el, INTSXP))[0];
  }
  if (ret == NA_INTEGER) {
    Rf_error("Expected a value for '%s'", name);
  }
  user_check_values_int(&ret, 1, min, max, name);
  return ret;
}
void user_check_values_double(double * value, size_t len,
                                  double min, double max, const char *name) {
  for (size_t i = 0; i < len; ++i) {
    if (ISNA(value[i])) {
      Rf_error("'%s' must not contain any NA values", name);
    }
  }
  if (min != NA_REAL) {
    for (size_t i = 0; i < len; ++i) {
      if (value[i] < min) {
        Rf_error("Expected '%s' to be at least %g", name, min);
      }
    }
  }
  if (max != NA_REAL) {
    for (size_t i = 0; i < len; ++i) {
      if (value[i] > max) {
        Rf_error("Expected '%s' to be at most %g", name, max);
      }
    }
  }
}
void user_check_values_int(int * value, size_t len,
                               double min, double max, const char *name) {
  for (size_t i = 0; i < len; ++i) {
    if (ISNA(value[i])) {
      Rf_error("'%s' must not contain any NA values", name);
    }
  }
  if (min != NA_REAL) {
    for (size_t i = 0; i < len; ++i) {
      if (value[i] < min) {
        Rf_error("Expected '%s' to be at least %g", name, min);
      }
    }
  }
  if (max != NA_REAL) {
    for (size_t i = 0; i < len; ++i) {
      if (value[i] > max) {
        Rf_error("Expected '%s' to be at most %g", name, max);
      }
    }
  }
}
void user_check_values(SEXP value, double min, double max,
                           const char *name) {
  size_t len = (size_t)length(value);
  if (TYPEOF(value) == INTSXP) {
    user_check_values_int(INTEGER(value), len, min, max, name);
  } else {
    user_check_values_double(REAL(value), len, min, max, name);
  }
}
SEXP user_list_element(SEXP list, const char *name) {
  SEXP ret = R_NilValue, names = getAttrib(list, R_NamesSymbol);
  for (int i = 0; i < length(list); ++i) {
    if (strcmp(CHAR(STRING_ELT(names, i)), name) == 0) {
      ret = VECTOR_ELT(list, i);
      break;
    }
  }
  return ret;
}
void odin_set_dim(SEXP target, int rank, ...) {
  SEXP r_dim = PROTECT(allocVector(INTSXP, rank));
  int *dim = INTEGER(r_dim);

  va_list ap;
  va_start(ap, rank);
  for (size_t i = 0; i < (size_t)rank; ++i) {
    dim[i] = va_arg(ap, int);
  }
  va_end(ap);

  setAttrib(target, R_DimSymbol, r_dim);
  UNPROTECT(1);
}
void* user_get_array_dim(SEXP user, bool is_integer, void * previous,
                         const char *name, int rank,
                         double min, double max, int *dest_dim) {
  SEXP el = user_get_array_check_rank(user, name, rank, previous == NULL);
  if (el == R_NilValue) {
    return previous;
  }

  dest_dim[0] = LENGTH(el);
  if (rank > 1) {
    SEXP r_dim = PROTECT(coerceVector(getAttrib(el, R_DimSymbol), INTSXP));
    int *dim = INTEGER(r_dim);

    for (size_t i = 0; i < (size_t) rank; ++i) {
      dest_dim[i + 1] = dim[i];
    }

    UNPROTECT(1);
  }

  el = PROTECT(user_get_array_check(el, is_integer, name, min, max));

  int len = LENGTH(el);
  void *dest = NULL;
  if (is_integer) {
    dest = R_Calloc(len, int);
    memcpy(dest, INTEGER(el), len * sizeof(int));
  } else {
    dest = R_Calloc(len, double);
    memcpy(dest, REAL(el), len * sizeof(double));
  }
  R_Free(previous);

  UNPROTECT(1);

  return dest;
}
void* user_get_array(SEXP user, bool is_integer, void * previous,
                     const char *name, double min, double max,
                     int rank, ...) {
  SEXP el = user_get_array_check_rank(user, name, rank, previous == NULL);
  if (el == R_NilValue) {
    return previous;
  }

  SEXP r_dim;
  int *dim;

  size_t len = LENGTH(el);
  if (rank == 1) {
    r_dim = PROTECT(ScalarInteger(len));
  } else {
    r_dim = PROTECT(coerceVector(getAttrib(el, R_DimSymbol), INTSXP));
  }
  dim = INTEGER(r_dim);

  va_list ap;
  va_start(ap, rank);
  for (size_t i = 0; i < (size_t) rank; ++i) {
    int dim_expected = va_arg(ap, int);
    if (dim[i] != dim_expected) {
      va_end(ap); // avoid a leak
      if (rank == 1) {
        Rf_error("Expected length %d value for '%s'", dim_expected, name);
      } else {
        Rf_error("Incorrect size of dimension %d of '%s' (expected %d)",
                 (int)i + 1, name, dim_expected);
      }
    }
  }
  va_end(ap);
  UNPROTECT(1);

  el = PROTECT(user_get_array_check(el, is_integer, name, min, max));

  void *dest = NULL;
  if (is_integer) {
    dest = R_Calloc(len, int);
    memcpy(dest, INTEGER(el), len * sizeof(int));
  } else {
    dest = R_Calloc(len, double);
    memcpy(dest, REAL(el), len * sizeof(double));
  }
  R_Free(previous);

  UNPROTECT(1);

  return dest;
}
SEXP user_get_array_check(SEXP el, bool is_integer, const char *name,
                          double min, double max) {
  size_t len = (size_t) length(el);
  if (is_integer) {
    if (TYPEOF(el) == INTSXP) {
      user_check_values_int(INTEGER(el), len, min, max, name);
    } else if (TYPEOF(el) == REALSXP) {
      el = PROTECT(coerceVector(el, INTSXP));
      user_check_values_int(INTEGER(el), len, min, max, name);
      UNPROTECT(1);
    } else {
      Rf_error("Expected a integer value for '%s'", name);
    }
  } else {
    if (TYPEOF(el) == INTSXP) {
      el = PROTECT(coerceVector(el, REALSXP));
      user_check_values_double(REAL(el), len, min, max, name);
      UNPROTECT(1);
    } else if (TYPEOF(el) == REALSXP) {
      user_check_values_double(REAL(el), len, min, max, name);
    } else {
      Rf_error("Expected a numeric value for '%s'", name);
    }
  }
  return el;
}
SEXP user_get_array_check_rank(SEXP user, const char *name, int rank,
                               bool required) {
  SEXP el = user_list_element(user, name);
  if (el == R_NilValue) {
    if (required) {
      Rf_error("Expected a value for '%s'", name);
    }
  } else {
    if (rank == 1) {
      if (isArray(el)) {
        Rf_error("Expected a numeric vector for '%s'", name);
      }
    } else {
      SEXP r_dim = getAttrib(el, R_DimSymbol);
      if (r_dim == R_NilValue || LENGTH(r_dim) != rank) {
        if (rank == 2) {
          Rf_error("Expected a numeric matrix for '%s'", name);
        } else {
          Rf_error("Expected a numeric array of rank %d for '%s'", rank, name);
        }
      }
    }
  }
  return el;
}
void interpolate_check_y(size_t nx, size_t ny, size_t i, const char *name_arg, const char *name_target) {
  if (nx != ny) {
    if (i == 0) {
      // vector case
      Rf_error("Expected %s to have length %d (for '%s')",
               name_arg, (int)nx, name_target);
    } else {
      // array case
      Rf_error("Expected dimension %d of %s to have size %d (for '%s')",
               (int)i, name_arg, (int)nx, name_target);
    }
  }
}
double scalar_real(SEXP x, const char * name) {
  if (Rf_length(x) != 1) {
    Rf_error("Expected a scalar for '%s'", name);
  }
  double ret = 0.0;
  if (TYPEOF(x) == INTSXP) {
    ret = INTEGER(x)[0];
  } else if (TYPEOF(x) == REALSXP) {
    ret = REAL(x)[0];
  } else {
    Rf_error("Expected a numeric value for '%s'", name);
  }
  return ret;
}
// This construction is to help odin
#ifndef CINTERPOLTE_CINTERPOLATE_H_
#endif


void * cinterpolate_alloc(const char *type, size_t n, size_t ny,
                          double *x, double *y, bool fail_on_extrapolate,
                          bool auto_clean) {
  typedef void* interpolate_alloc_t(const char *, size_t, size_t,
                                    double*, double*, bool, bool);
  static interpolate_alloc_t *fun;
  if (fun == NULL) {
    fun = (interpolate_alloc_t*)
      R_GetCCallable("cinterpolate", "interpolate_alloc");
  }
  return fun(type, n, ny, x, y, fail_on_extrapolate, auto_clean);
}


int cinterpolate_eval(double x, void *obj, double *y) {
  typedef int interpolate_eval_t(double, void*, double*);
  static interpolate_eval_t *fun;
  if (fun == NULL) {
    fun = (interpolate_eval_t*)
      R_GetCCallable("cinterpolate", "interpolate_eval");
  }
  return fun(x, obj, y);
}


void cinterpolate_free(void *obj) {
  typedef int interpolate_free_t(void*);
  static interpolate_free_t *fun;
  if (fun == NULL) {
    fun = (interpolate_free_t*)
      R_GetCCallable("cinterpolate", "interpolate_free");
  }
  fun(obj);
}
