## Automatically generated by odin 1.5.11 - do not edit
ocaode_ <- R6::R6Class(
  "odin_model",
  cloneable = FALSE,

  private = list(
    ptr = NULL,
    use_dde = NULL,

    odin = NULL,
    variable_order = NULL,
    output_order = NULL,
    n_out = NULL,
    ynames = NULL,
    interpolate_t = NULL,
    cfuns = list(
      rhs_dde = "ocaode_rhs_dde",
      rhs_desolve = "ocaode_rhs_desolve",
      initmod_desolve = "ocaode_initmod_desolve",
      output_dde = "ocaode_output_dde"),
    dll = "OCA1",
    user = c("BB", "birthrisk", "exmigrate", "immigration", "migrage",
             "nage", "nnat", "npost", "nprot", "nrisk", "nstrain",
             "Pmigr_post", "Pmigr_prot", "Pmigr_risk", "Pmigr_strain",
             "popdat", "popinitA", "popinitE", "popinitL", "popinitS",
             "popinitT", "popinitU", "r", "RiskHazardData", "ttp",
             "detect_asymp", "detect_symp", "foi", "mortality_treated",
             "mortality_untreated", "progn_fast", "progn_posttb",
             "progn_slow", "progn_symp", "relapse", "stabilization",
             "treatment_inversedurn"),

    ## This is never called, but is used to ensure that R finds our
    ## symbols that we will use from the package; without this they
    ## cannot be found by dynamic lookup now that we use the package
    ## FFI registration system.
    registration = function() {
      if (FALSE) {
        .C("ocaode_rhs_dde", package = "OCA1")
        .C("ocaode_rhs_desolve", package = "OCA1")
        .C("ocaode_initmod_desolve", package = "OCA1")
        .C("ocaode_output_dde", package = "OCA1")
      }
    },

    ## This only does something in delay models
    set_initial = function(t, y, use_dde) {
      .Call("ocaode_set_initial", private$ptr, t, y, use_dde,
            PACKAGE= "OCA1")
    },

    update_metadata = function() {
      meta <- .Call("ocaode_metadata", private$ptr,
                    PACKAGE = "OCA1")
      private$variable_order <- meta$variable_order
      private$output_order <- meta$output_order
      private$n_out <- meta$n_out
      private$ynames <- private$odin$make_names(
        private$variable_order, private$output_order, FALSE)
      private$interpolate_t <- meta$interpolate_t
    }
  ),

  public = list(
    initialize = function(..., user = list(...), use_dde = FALSE,
                          unused_user_action = NULL) {
      private$odin <- asNamespace("odin")
      private$ptr <- .Call("ocaode_create", user, PACKAGE = "OCA1")
      self$set_user(user = user, unused_user_action = unused_user_action)
      private$use_dde <- use_dde
      private$update_metadata()
    },

    ir = function() {
      path_ir <- system.file("odin/ocaode.json", mustWork = TRUE,
                             package = "OCA1")
      json <- readLines(path_ir)
      class(json) <- "json"
      json
    },

    ## Do we need to have the user-settable args here? It would be
    ## nice, but that's not super straightforward to do.
    set_user = function(..., user = list(...), unused_user_action = NULL) {
      private$odin$support_check_user(user, private$user, unused_user_action)
      .Call("ocaode_set_user", private$ptr, user, PACKAGE = "OCA1")
      private$update_metadata()
    },

    ## This might be time sensitive and, so we can avoid computing
    ## it. I wonder if that's an optimisation we should drop for now
    ## as it does not seem generally useful. This would bring us
    ## closer to the js version which requires that we always pass the
    ## time in.
    initial = function(t) {
      .Call("ocaode_initial_conditions", private$ptr, t, PACKAGE = "OCA1")
    },

    rhs = function(t, y) {
      .Call("ocaode_rhs_r", private$ptr, t, y, PACKAGE = "OCA1")
    },

    deriv = function(t, y) {
      self$rhs(t, y)
    },

    contents = function() {
      .Call("ocaode_contents", private$ptr, PACKAGE = "OCA1")
    },

    transform_variables = function(y) {
      private$odin$support_transform_variables(y, private)
    },

    engine = function() {
      "c"
    },

    run = function(t, y = NULL, ..., use_names = TRUE) {
      private$odin$wrapper_run_ode(
        self, private, t, y, ..., use_names = use_names)
    }
  ))


ocaode <- function(..., user = list(...), use_dde = FALSE,
                     unused_user_action = NULL) {
  asNamespace("odin")$deprecated_constructor_call("ocaode")
  ocaode_$new(user = user, use_dde = use_dde,
                unused_user_action = unused_user_action)
}
class(ocaode) <- "odin_generator"
attr(ocaode, "generator") <- ocaode_
