name: R Package Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  test:
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - { os: ubuntu-latest, r: '4.3', rspm: 'https://packagemanager.r-project.org/all/latest' }
          - { os: macos-latest, r: '4.3', rspm: 'https://packagemanager.r-project.org/all/latest' }
          - { os: windows-latest, r: '4.3', rspm: 'https://packagemanager.r-project.org/all/latest' }

    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: ~/.cache/R
          key: ${{ runner.os }}-r-${{ matrix.config.r }}-${{ hashFiles('DESCRIPTION') }}
          restore-keys: |
            ${{ runner.os }}-r-${{ matrix.config.r }}-
            ${{ runner.os }}-r-

      - uses: r-lib/actions/setup-r@v2 # Use latest v2
        with:
          r-version: ${{ matrix.config.r }} # Use matrix.config.r
          use-rspm: true
          sudo: false # Explicitly disable sudo 
      - name: Install dependencies
        run: |
          Rscript -e 'install.packages(c("remotes", "rcmdcheck", "testthat"), repos = "https://cloud.r-project.org/")'
          Rscript -e 'remotes::install_deps(dependencies = TRUE)'

      - name: Run Tests
        run: Rscript -e 'testthat::test_local()'
